import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('workbench task panel product boundary', () => {
  const source = readFileSync(new URL('./workbenchPanels.ts', import.meta.url), 'utf8')
  const workbenchSource = ['./workbench.ts', './workbenchShell.ts', './workbenchIcons.ts'].map(file => readFileSync(new URL(file, import.meta.url), 'utf8')).join('\n')
  const terminalPanelSource = readFileSync(new URL('./terminalPanel.ts', import.meta.url), 'utf8')
  const styles = readFileSync(new URL('./styles.css', import.meta.url), 'utf8')

  it('does not expose internal execution logs in the product panel', () => {
    expect(source).not.toContain('活动证据')
    expect(source).not.toContain('条证据')
    expect(source).not.toContain('renderWorkActivityRow')
    expect(source).not.toContain('activity.path')
    expect(source).not.toContain('activity.attempt')
  })

  it('keeps only semantic steps, user action, and result sections', () => {
    expect(source).toContain("section('步骤')")
    expect(source).toContain("section('终端进程'")
    expect(source).toContain("'需要你处理'")
    expect(source).toContain("'结果'")
  })

  it('keeps task surfaces independent from the work drawer', () => {
    expect(workbenchSource).not.toContain('task-companion')
    expect(workbenchSource).toContain('id="work-plan-dock"')
    expect(workbenchSource.match(/id="inspector-toggle"/g) ?? []).toHaveLength(1)
    expect(workbenchSource).toContain('class="icon-button work-drawer-toggle" id="inspector-toggle"')
    expect(workbenchSource.indexOf('</main>')).toBeLessThan(workbenchSource.indexOf('id="inspector-toggle"'))
    expect(workbenchSource).not.toContain('id="inspector-close"')
    expect(workbenchSource).not.toContain("icon('summary')")
    expect(workbenchSource).not.toContain('task-panel-toggle')
    expect(styles).not.toContain('.task-companion')
    expect(workbenchSource).toContain('createComputerControls(app, bridge')
    expect(styles).toContain('.conversation.running time::after')
    expect(styles).not.toContain('runtime-status-pulse')
    expect(workbenchSource).not.toContain('inspectorDismissedConversationIds')
    expect(workbenchSource).toContain('<div class="workbench-surface">')
    expect(workbenchSource.indexOf('<main class="main-panel"')).toBeLessThan(workbenchSource.indexOf('<aside class="inspector"'))
    expect(styles).toContain('.workbench-surface { position: relative; z-index: 2; display: flex;')
    expect(styles).toMatch(/\.sidebar \{[\s\S]*?z-index: 1;/)
    expect(styles).toContain('box-shadow: -3px 0 10px -8px')
    expect(styles).not.toMatch(/\.sidebar \{[^}]*box-shadow: [1-9]\d*px 0/)
    expect(styles).toContain('.inspector { position: relative;')
    expect(styles).toContain('grid-template-columns: 304px minmax(0, 1fr);')
    expect(styles).toContain('--sidebar-row-height: 34px;')
    expect(styles).toContain('--sidebar-row-radius: 10px;')
    expect(styles).toContain('--sidebar-row-padding: 8px;')
    expect(workbenchSource).toContain('<div class="window-sidebar-control">')
    expect(workbenchSource).toContain('<button class="icon-button window-sidebar-toggle" id="sidebar-toggle"')
    expect(workbenchSource).toContain('<div class="sidebar-titlebar-drag-region" aria-hidden="true"></div>')
    expect(workbenchSource.match(/id="sidebar-toggle"/g) ?? []).toHaveLength(1)
    expect(workbenchSource).not.toContain('id="sidebar-reopen-toggle"')
    expect(workbenchSource).not.toContain('class="sidebar-heading"')
    expect(styles).toContain('width: 41px; height: var(--titlebar-height); padding-bottom: 1px; place-items: center; pointer-events: auto; -webkit-app-region: no-drag;')
    expect(styles).toContain('.platform-macos .sidebar { -webkit-app-region: no-drag; }')
    expect(styles).toContain('.platform-macos .sidebar-titlebar-drag-region { position: absolute; top: 0; right: 0; left: 131px;')
    expect(styles).toContain('.platform-macos .window-sidebar-control { left: 90px; }')
    expect(styles).toContain('.platform-macos .desktop-shell.sidebar-collapsed .topbar { padding-left: 142px; }')
    expect(styles).toContain('justify-content: flex-start; gap: 8px; padding: 0 var(--window-actions-inset) 0 24px;')
    expect(workbenchSource).toContain("const sidebarCollapsedStorageKey = 'turboflux.sidebar.collapsed:v1'")
    expect(workbenchSource).toContain("event.key.toLowerCase() === 'b'")
    expect(styles).toContain('.desktop-shell.sidebar-collapsed { grid-template-columns: 0 minmax(0, 1fr); }')
    expect(styles).toContain('transition: grid-template-columns var(--motion-emphasis) var(--ease-enter);')
    expect(styles).toContain('.sidebar-history { position: relative; display: flex; min-height: 0; flex: 1 1 auto; flex-direction: column; padding-top: 0; border-top: 0; }')
    expect(styles).toContain('.conversation time { display: none;')
    expect(styles).toContain('.sidebar-nav-item.active { color: #292a27; background: #e9e9e7;')
    expect(styles).not.toContain('.conversation-row.active { animation:')
    expect(workbenchSource).toContain("${icon('newConversation')}<span>新建任务</span>")
    expect(workbenchSource).toContain("data-view=\"automations\"")
    expect(workbenchSource).toContain("${icon('pluginNav')}<span>插件</span>")
    expect(workbenchSource).toContain("taskHost.className = 'workspace-task-group-conversations'")
    expect(workbenchSource).toContain("taskHostInner.className = 'workspace-task-group-conversations-inner'")
    expect(workbenchSource).toContain("taskHost.classList.toggle('expanded', nextExpanded)")
    expect(workbenchSource).toContain('taskHost.inert = !nextExpanded')
    expect(workbenchSource).toContain('renderedConversationListSignature = conversationListSignature()')
    expect(styles).toContain('grid-template-rows: 0fr; opacity: 0; pointer-events: none; transform: translateY(-4px);')
    expect(styles).toContain('.workspace-task-group-conversations.expanded { grid-template-rows: 1fr;')
    expect(styles).toContain('.workspace-task-group-conversations-inner { min-height: 0; overflow: hidden; }')
    expect(workbenchSource).toContain("const workbenchSurface = app.querySelector<HTMLDivElement>('.workbench-surface')!")
    expect(workbenchSource).toContain('return workbenchSurface.clientWidth')
    expect(styles).not.toContain('.desktop-shell.inspector-open .main-panel { margin-right:')
  })

  it('keeps conversation navigation independent from the reading axis', () => {
    expect(workbenchSource).toContain('id="conversation-navigator"')
    expect(workbenchSource).not.toContain("conversationNavigator.style.setProperty('--conversation-navigator-left'")
    expect(workbenchSource).toContain('conversationNavigatorMarkerVisual(index, previewIndex)')
    expect(workbenchSource).toContain('jumpToConversationNavigatorTarget(target)')
    expect(workbenchSource).toContain('pairConversationNavigatorTasks')
    expect(workbenchSource).toContain('pairs.length >= conversationNavigatorMinimumItems')
    expect(workbenchSource).toContain('transcriptBounds.left - mainBounds.left >= 48')
    expect(workbenchSource).toContain("jumpToConversationNavigatorTarget(entry.target, 'auto')")
    expect(workbenchSource).toContain("event.key === 'ArrowUp' || event.key === 'ArrowDown'")
    expect(workbenchSource).not.toContain('minorCount / 56')
    expect(styles).toContain('.conversation-navigator { position: absolute;')
    expect(styles).toContain('left: 16px;')
    expect(styles).toContain('height: 10px; min-height: 10px; flex: 0 0 10px;')
    expect(styles).toContain('width: 26px; height: 2px;')
    expect(styles).toContain('scaleX(var(--conversation-navigator-marker-scale, .2308))')
    expect(styles).toContain('max-height: min(70vh, 640px, calc(100% - 32px));')
    expect(styles).toContain('.conversation-navigator-markers.scrubbing')
    expect(styles).toContain('.conversation-navigator-popover')
    expect(styles).not.toContain('.conversation-navigator-track::before')
    expect(styles).not.toContain('.conversation-navigator-viewport')
  })

  it('keeps the topbar focused on the current task title', () => {
    expect(workbenchSource).toContain('<div class="breadcrumb" id="breadcrumb"><strong id="breadcrumb-title">工作台</strong></div>')
    expect(workbenchSource).not.toContain('id="breadcrumb-workspace"')
    expect(workbenchSource).toContain("breadcrumb.setAttribute('aria-label', title)")
  })

  it('coordinates task entry and creation without a top loading line', () => {
    expect(workbenchSource).toContain("function beginConversationTransition(kind: 'switch' | 'new'")
    expect(workbenchSource).toContain('function finishConversationTransition(transitionId: number, succeeded: boolean)')
    expect(workbenchSource).toContain("beginConversationTransition('switch', id)")
    expect(workbenchSource).toContain("beginConversationTransition('new', '', newTaskButton)")
    expect(workbenchSource).toContain("beginConversationTransition('new', '', create)")
    expect(workbenchSource).toContain("mainScroll.setAttribute('aria-busy', 'true')")
    expect(styles).toContain('.conversation-row.navigation-pending::after,')
    expect(styles).toContain('.main-scroll.conversation-transition-leaving > .transcript,')
    expect(styles).toContain('@keyframes conversation-surface-enter')
    expect(workbenchSource).not.toContain('conversation-transition-indicator')
    expect(styles).not.toContain('.conversation-transition-progress')
    expect(styles).not.toContain('@keyframes conversation-loading-progress')
  })

  it('provides a resizable multi-session terminal below the workbench', () => {
    expect(workbenchSource).toContain('class="icon-button terminal-toggle" id="terminal-toggle"')
    expect(workbenchSource).toContain('class="terminal-panel" id="terminal-panel"')
    expect(workbenchSource).toContain('createTerminalPanel(')
    expect(workbenchSource).toContain("event.key.toLowerCase() === 'j'")
    expect(terminalPanelSource).toContain('role="separator" tabindex="0" aria-orientation="horizontal"')
    expect(terminalPanelSource).toContain("bridge.terminalCreate()")
    expect(terminalPanelSource).toContain("bridge.terminalResize(client.session.id, cols, rows)")
    expect(terminalPanelSource).toContain("bridge.terminalClose(sessionId)")
    expect(terminalPanelSource).toContain("bridge.onTerminalEvent(handleTerminalEvent)")
    expect(terminalPanelSource).toContain("new Terminal({")
    expect(terminalPanelSource).toContain("new FitAddon()")
    expect(terminalPanelSource).not.toContain('terminal-shell-badge')
    expect(terminalPanelSource).not.toContain('session.shell')
    expect(terminalPanelSource).not.toContain('session.title')
    expect(terminalPanelSource).toContain('const displayTitle = `会话 ${index + 1}`')
    expect(terminalPanelSource).toContain("terminalIcon.innerHTML = panelIcon('terminal')")
    expect(styles).toContain('.terminal-tab-icon { display: inline-grid;')
    expect(styles).not.toContain('.terminal-tab-status')
    expect(styles).toContain('.terminal-panel.open { height: var(--terminal-panel-height);')
    expect(styles).toContain('.terminal-resize-handle { position: absolute;')
    expect(styles).toContain('.terminal-tab-slot.active')
    expect(styles).toContain('html[data-theme="dark"] .terminal-panel { background: #171717; }')
  })

  it('uses a quiet three-state composer action', () => {
    expect(workbenchSource).toContain('presentComposerRunButton({')
    expect(workbenchSource).toContain('submissionPauseRequested = true')
    expect(workbenchSource).toContain("app.querySelector('#run-button')?.addEventListener('click', activateRunButton)")
    expect(workbenchSource).toContain("sendUp: '<svg")
    expect(workbenchSource).toContain("pauseBlock: '<svg")
    expect(styles).toContain('.run-button { display: inline-grid; width: 29px; height: 29px;')
    expect(styles).toContain('.run-button[data-action="pause"] { color: #fff; background: #20211f; }')
    expect(styles).not.toContain('#5a49e6')
    expect(styles).toContain('.run-button:disabled { color: #a6a6a1; background: #e3e3df;')
    expect(styles).toContain('@keyframes run-button-icon-enter')
    expect(styles).not.toContain('runtime-button-breathe')
  })

  it('keeps approval switching on the composer input shortcut', () => {
    const inputHandler = workbenchSource.slice(
      workbenchSource.indexOf("taskInput.addEventListener('keydown'"),
      workbenchSource.indexOf("taskInput.addEventListener('paste'"),
    )
    expect(inputHandler).toContain("event.key === 'Tab'")
    expect(inputHandler).toContain('event.shiftKey')
    expect(inputHandler).toContain('event.preventDefault()')
    expect(inputHandler).toContain('event.stopPropagation()')
    expect(inputHandler).toContain('void selectApprovalPolicy(nextPolicy)')
    expect(workbenchSource).not.toContain('keyboardTarget instanceof Node && composerCard.contains(keyboardTarget)')
  })

  it('folds terminal task internals behind the final delivery', () => {
    expect(workbenchSource).toContain('function applyCompletedTaskFolding()')
    expect(workbenchSource).toContain('Boolean(executionOutcomeFromWorkRunStatus(run?.status))')
    expect(workbenchSource).toContain("item.dataset.finalDelivery === 'true'")
    expect(workbenchSource).toContain("label.textContent = expanded ? '收起过程' : '处理过程'")
    expect(workbenchSource).toContain("input.querySelector<HTMLElement>('.message-row.user')?.dataset.timestamp")
    expect(workbenchSource).toContain("finalAnswer.querySelector<HTMLElement>('.message-row.assistant')?.dataset.timestamp")
    expect(workbenchSource).toContain('completedTaskTurnDuration(startedAt, completedAt)')
    expect(workbenchSource).not.toContain("finalAnswer.querySelector<HTMLElement>('.message-usage')")
    expect(workbenchSource).not.toContain('duration.textContent = presentWorkRun(run).duration')
    expect(workbenchSource).toContain('return duration')
    expect(workbenchSource).toContain('function setTaskTurnRegionExpanded(')
    expect(workbenchSource).toContain('function setTaskTurnRegionExpandedFromDisclosure(')
    expect(workbenchSource).toContain('const disclosureViewportTop = disclosure.getBoundingClientRect().top')
    expect(workbenchSource).toContain('transcriptFollowState = suspendTranscriptFollow(transcriptFollowState)')
    expect(workbenchSource).toContain('transcript.scrollTop += disclosure.getBoundingClientRect().top - disclosureViewportTop')
    expect(workbenchSource).toContain('const animateAutomaticCollapse = taskRunSeenActiveIds.delete(runId)')
    expect(workbenchSource).toContain("region.className = 'task-turn-fold-region'")
    expect(workbenchSource).toContain("content.className = 'task-turn-fold-content'")
    expect(styles).toContain('.task-turn-disclosure')
    expect(styles).toContain('.task-turn-fold-region.expanded')
    expect(styles).toContain('grid-template-rows: 1fr')
    expect(styles).toContain('.task-turn-fold-content > .linear-flow-item[data-flow-gap="content"] { margin-top: var(--content-block-gap); }')
    expect(styles).toContain('.task-turn-fold-content > .linear-flow-item[data-flow-gap="turn"] { margin-top: var(--content-turn-gap); }')
    expect(styles).not.toContain('.task-turn-intermediate[hidden]')
  })

  it('opens the work drawer on a quiet browser-only landing page', () => {
    expect(workbenchSource).not.toContain("{ tab: 'activity', label: '任务', iconName: 'activity' }")
    expect(workbenchSource).toContain("{ tab: 'browser', label: '浏览器', iconName: 'browser' }")
    expect(workbenchSource).not.toContain("{ tab: 'outputs', label: '产物', iconName: 'outputs' }")
    expect(workbenchSource).toContain("{ tab: 'context', label: '上下文', iconName: 'context' }")
    expect(workbenchSource).toContain("{ tab: 'git', label: '版本', iconName: 'git' }")
    expect(workbenchSource).toContain('function renderInspectorLanding()')
    expect(workbenchSource).toContain('data-inspector-entry="browser"')
    expect(workbenchSource).toContain("setInspectorWidth(INSPECTOR_MINIMUM_WIDTH, false, 'regular')")
    expect(workbenchSource).toContain('else showInspectorLanding()')
    expect(styles).toContain('.inspector.inspector-landing-mode .inspector-header { display: none; }')
    expect(styles).toContain('.inspector-landing { display: flex;')
    expect(styles).toContain('.inspector-landing-actions { display: grid; width: max-content;')
    expect(styles).toContain('.inspector-landing-entry { display: flex; min-width: 132px;')
    expect(styles).toContain('justify-content: center; gap: 10px;')
    expect(styles).not.toContain('.inspector-landing-entry:hover, .inspector-landing-entry:focus-visible { color: var(--text); background: var(--surface-selected); transform: translateX')
    expect(styles).not.toContain('.desktop-shell.inspector-open .work-drawer-toggle')
    expect(workbenchSource).not.toContain("tab: 'terminal'")
    expect(workbenchSource).not.toContain('createWorkOverviewSection')
    expect(workbenchSource).not.toContain('renderWorkOverview')
    expect(workbenchSource).toContain('? { x: 0, y: 0, width: 0, height: 0 }')
    expect(workbenchSource).not.toContain('empty-orbit')
    expect(workbenchSource).not.toContain("glyph.textContent = '◎'")
    expect(workbenchSource).not.toContain("{ tab: 'overview', label: '概览'")
    expect(styles).toContain('.inspector-nav { display: flex;')
    expect(styles).not.toContain('.work-overview-')
    expect(styles).toContain('.empty-module-icon .icon')
    expect(styles).not.toContain('.empty-orbit')
    expect(workbenchSource).toContain('id="inspector-tabs" role="tablist"')
    expect(workbenchSource).toContain('id="inspector-module-menu" role="menu"')
    expect(workbenchSource).toContain('function renderInspectorChrome()')
    expect(workbenchSource).not.toContain('className = \'inspector-browser-tabbar\'')
    expect(workbenchSource).not.toContain('class="inspector-bottom"')
    expect(workbenchSource).toContain('function artifactIconName(')
    expect(workbenchSource).not.toContain('function artifactGlyph(')
    expect(workbenchSource).toContain('glyph.innerHTML = icon(artifactIconName(artifact.kind))')
    expect(styles).toContain('.inspector-tabs { display: flex;')
    expect(styles).toContain('.inspector-module-menu.visible')
    expect(styles).not.toContain('.inspector-primary-tabs')
    expect(styles).not.toContain('.inspector-utility-tabs')
    expect(styles).toContain('.context-metrics > div:first-child, .git-metrics > div:first-child')
    expect(source).toContain('<span>上下文输入</span>')
    expect(source).toContain('<span>新增输出</span>')
    expect(source).toContain('<span>缓存命中</span>')
    expect(styles).toContain('.context-segment:last-child { border-bottom: 0; }')
    expect(styles).toContain('.git-branch-symbol svg')
    expect(source).toContain("unavailable: '不可用'")
    expect(source).not.toContain('class="git-branch-symbol">⑂')
  })

  it('restores normal drawer width outside browser landscape mode', () => {
    expect(workbenchSource).toContain("browserLayoutMode: BrowserViewportMode = 'portrait'")
    expect(workbenchSource).toContain("'turboflux.inspector.right-panel-width:v3'")
    expect(workbenchSource).toContain("event.type === 'layout-request'")
    expect(workbenchSource).toContain("? 'full'")
    expect(workbenchSource).toContain("persist && mode === 'regular'")
    const showInspector = workbenchSource.slice(workbenchSource.indexOf('function showInspectorPanelTab('), workbenchSource.indexOf('function openInspector('))
    expect(showInspector).toContain("if (!wasOpen) applyInspectorWidthForTab(panelTab.inspectorTab)")
    expect(showInspector.indexOf("if (!wasOpen) applyInspectorWidthForTab(panelTab.inspectorTab)")).toBeLessThan(showInspector.indexOf("shell.classList.add('inspector-open')"))
    expect(showInspector).toContain('applyInspectorWidthForCurrentTab()')
    const closeInspector = workbenchSource.slice(workbenchSource.indexOf('function closeInspector('), workbenchSource.indexOf('function updateInspectorToggleState('))
    expect(closeInspector).toContain("browserLayoutMode = 'portrait'")
    expect(styles).toContain('transition: width var(--motion-panel) var(--ease-panel)')
    expect(styles).toContain('opacity var(--motion-panel) var(--ease-panel)')
    expect(styles).toContain('.inspector-frame { position: absolute;')
    expect(styles).toContain('width: 100%; min-width: 0; min-height: 0; flex-direction: column;')
    expect(styles).not.toContain('.desktop-shell.inspector-open .inspector { transform:')
    expect(styles).toContain('.desktop-shell.inspector-full-width .inspector-edge-shadow')
    expect(styles).not.toContain('inspector-fast-closing')
  })

  it('uses top-level closable tabs for browser pages and change details', () => {
    expect(workbenchSource).toContain("kind: 'module' | 'browser' | 'artifact' | 'change'")
    expect(workbenchSource).toContain('function openArtifactInspectorTab(')
    expect(workbenchSource).toContain('function openChangeInspectorTab(')
    expect(workbenchSource).toContain("isPreview: true")
    expect(workbenchSource).toContain("tab.addEventListener('dblclick'")
    expect(workbenchSource).toContain('adjacentInspectorTabId(tabIds, tabId)')
    expect(workbenchSource).toContain('reorderInspectorTabIds(')
    expect(workbenchSource).toContain("activePanelTab?.kind === 'artifact'")
    expect(workbenchSource).toContain("activePanelTab?.kind === 'change'")
    expect(workbenchSource).not.toContain("back.className = 'inspector-back'")
    expect(styles).toContain('.inspector-tab-slot { position: relative;')
    expect(styles).toContain('width 180ms cubic-bezier(.23,1,.32,1)')
    expect(styles).toContain('.inspector-header { position: relative; z-index: 2; display: flex; min-height: var(--titlebar-height); flex: 0 0 var(--titlebar-height);')
    expect(workbenchSource).toContain('class="inspector-resize-handle" id="inspector-resize-handle" role="separator" tabindex="0"')
  })

  it('uses distinct semantic icons for every approval policy', () => {
    expect(workbenchSource).toContain("ask: icon('approvalAsk')")
    expect(workbenchSource).toContain("agent: icon('approvalAgent')")
    expect(workbenchSource).toContain("full: icon('approvalFull')")
    expect(workbenchSource).toContain('approvalFull: \'<svg viewBox="0 0 24 24"><path d="M12 3.5 19 6v5.2c0 4.1-2.5 7.6-7 9.3-4.5-1.7-7-5.2-7-9.3V6z"/><path d="M12 8v5"/><path d="M12 16.5h.01"/></svg>\'')
    expect(workbenchSource).not.toContain('id="capability-tab"')
    expect(workbenchSource).toContain('class="approval-policy-icon" id="approval-icon"')
    expect(workbenchSource).toContain('approvalIcon.innerHTML = approvalPolicyIcon(snapshot.runtime.approvalPolicy)')
    expect(workbenchSource).not.toContain('approval-status-dot')
    expect(workbenchSource).not.toContain('♢')
  })

  it('marks full execution as a red danger state in the pill and selector', () => {
    expect(workbenchSource).toContain("full: '全权执行'")
    expect(workbenchSource).toContain('row.dataset.policy = policy')
    expect(styles).toContain('.approval-pill[data-policy="full"] { color: #b42318;')
    expect(styles).toContain('.approval-pill[data-policy="full"] { color: #b42318; background: transparent; box-shadow: none; }')
    expect(styles).toContain('.approval-menu .composer-menu-row[data-policy="full"] { color: #b42318; background: transparent; }')
    expect(styles).not.toContain('background: rgba(180,35,24')
    expect(styles).not.toContain('background: rgba(239,68,68')
    expect(styles).not.toContain('box-shadow: inset 0 0 0 1px rgba(180,35,24,.12)')
    expect(styles).not.toContain('box-shadow: inset 0 0 0 1px rgba(255,116,108,.16)')
  })

  it('shows semantic order, dependencies, parallel work, and historical runs', () => {
    expect(source).toContain('orderedWorkSteps(run, step.childIds)')
    expect(source).toContain("dependencyDetail.className = 'work-step-dependencies'")
    expect(source).toContain("parallel ? '并行' : ''")
    expect(source).toContain("navigation.className = 'work-run-history'")
    expect(source).toContain('isCurrentRun &&')
  })

  it('does not repeat the full request in the task panel', () => {
    expect(source).not.toContain('run.objective')
    expect(source).toContain('const presentation = presentWorkRun(run)')
    expect(source).toContain('title.textContent = presentation.statusLabel')
    expect(source).toContain('presentation.currentStep ? presentation.currentStep.title')
  })

  it('renders workspace skill metadata as text instead of HTML', () => {
    expect(source).toContain("skillName.textContent = skill ? skill.name : '插件'")
    expect(source).not.toContain("skillRow.innerHTML = `<span><strong>${skill ? skill.name")
  })

  it('prefers semantic work stages and keeps tool categories as fallback details', () => {
    expect(workbenchSource).not.toContain('function createExecutionGroup(')
    expect(workbenchSource).not.toContain('function updateExecutionGroup(')
    expect(workbenchSource).toContain('createLinearTaskFlowRenderer(transcript, {')
    expect(workbenchSource).toContain('renderCanonicalTaskFlow(true)')
    expect(workbenchSource).toContain('applyConversationViewEvent(previousView, event.event)')
  })
})
