import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { shouldPlayTaskCompletionSound } from './taskCompletionSound'
import {
  taskCompletionNotificationDelivery,
  taskCompletionNotificationPresentation,
} from './taskCompletionNotification'
import { assertExecutableConversationWorkspace } from './conversationWorkspacePolicy'
import { DEFAULT_DESKTOP_DEV_PORT, resolveDesktopDevServer } from '../../scripts/desktop-dev-server.mjs'

const readDesktopFile = (name: string) => {
  const files = name === 'renderer/workbench.ts' ? [name, 'renderer/workbenchShell.ts', 'renderer/workbenchIcons.ts'] : [name]
  return files.map(file => readFileSync(new URL(`./${file}`, import.meta.url), 'utf8')).join('\n')
}

describe('desktop surface contract', () => {
  it('keeps imported unbound conversation history readable but non-executable', () => {
    expect(() => assertExecutableConversationWorkspace('turboflux-unbound:workspace-12345678')).toThrow('工作区尚未绑定')
    expect(() => assertExecutableConversationWorkspace('/tmp/ready-workspace')).not.toThrow()
  })

  it('builds agent-core before every desktop build entry point', () => {
    const desktopManifest = JSON.parse(readDesktopFile('package.json')) as { scripts?: Record<string, string> }
    const workspaceManifest = JSON.parse(
      readFileSync(new URL('../../package.json', import.meta.url), 'utf8'),
    ) as { scripts?: Record<string, string> }

    expect(desktopManifest.scripts?.['build:core']).toBe('npm --prefix ../.. run build:core')
    expect(desktopManifest.scripts?.build).toBe('npm run build:core && npm run build:app')
    expect(desktopManifest.scripts?.['package:dir']).toContain('npm run build')
    expect(desktopManifest.scripts?.['package:mac']).toContain('npm run package:mac:unverified')
    expect(desktopManifest.scripts?.['package:mac:unverified']).toContain('npm run build')
    expect(desktopManifest.scripts?.['package:win']).toContain('npm run build')
    expect(desktopManifest.scripts?.['package:linux']).toContain('npm run build')
    expect(workspaceManifest.scripts?.['build:desktop']).toBe('npm run build:core && npm run build:desktop:app')
    expect(workspaceManifest.scripts?.['build:all']?.indexOf('npm run build:core')).toBe(0)
    expect(workspaceManifest.scripts?.['build:all']).toContain('npm run build:desktop:app')
  })

  it('plays the global desktop sound only after successful task completion', () => {
    const main = readDesktopFile('main.mjs')
    const renderer = readDesktopFile('renderer/workbench.ts')

    expect(shouldPlayTaskCompletionSound({ type: 'conversation-run', status: 'completed' })).toBe(true)
    expect(shouldPlayTaskCompletionSound({ type: 'conversation-run', status: 'failed' })).toBe(false)
    expect(shouldPlayTaskCompletionSound({ type: 'conversation-run', status: 'interrupted' })).toBe(false)
    expect(shouldPlayTaskCompletionSound({ type: 'snapshot' })).toBe(false)
    expect(renderer).toContain('if (shouldPlayTaskCompletionSound(event)) void playTaskCompletionChime()')
    expect(renderer).toContain("lifetime.listen(window, 'pointerdown', primeCompletionSound")
    expect(main).not.toContain('shell.beep()')
  })

  it('shows a system completion notification in both foreground and background', () => {
    const main = readDesktopFile('main.mjs')
    const preload = readDesktopFile('preload.cjs')
    const renderer = readDesktopFile('renderer/workbench.ts')
    const styles = readDesktopFile('renderer/styles.css')

    expect(taskCompletionNotificationPresentation({ type: 'conversation-run', status: 'completed' }, '后台整理')?.body)
      .toBe('后台整理 已完成，点击查看结果。')
    expect(taskCompletionNotificationPresentation({ type: 'conversation-run', status: 'failed' })).toBeNull()
    expect(taskCompletionNotificationDelivery({ type: 'conversation-run', status: 'completed' }, true).showSystemNotification).toBe(true)
    expect(taskCompletionNotificationDelivery({ type: 'conversation-run', status: 'completed' }, false).showSystemNotification).toBe(true)
    expect(main).toContain("import { app, BrowserWindow, dialog, ipcMain as electronIpcMain, Menu, nativeImage, net, Notification, powerMonitor, protocol, safeStorage, shell } from 'electron'")
    expect(main).toContain('showTaskCompletionNotification(event)')
    expect(main).toContain('if (!delivery.showSystemNotification) return')
    expect(main).toContain('if (delivery.requestBackgroundAttention) requestBackgroundAttention()')
    expect(main).toContain('Notification.isSupported()')
    expect(main).toContain("app.dock?.bounce('informational')")
    expect(main).toContain('mainWindow.flashFrame(true)')
    expect(main).toContain('void revealCompletedTask(event.conversationId)')
    expect(main).toContain("workbenchWindow.webContents.send('desktop:navigation-intent', intent)")
    expect(main).toContain('automationApprovalNavigationIntent({')
    expect(preload).toContain("ipcRenderer.on('desktop:navigation-intent', handler)")
    expect(renderer).toContain('await automationsView?.navigate(intent)')
    expect(renderer).not.toContain('task-completion-banner')
    expect(renderer).not.toContain('showTaskCompletionBanner')
    expect(styles).not.toContain('.task-completion-banner')
  })

  it('packages every local module imported by the desktop runtime host', () => {
    const builder = readDesktopFile('electron-builder.yml')
    const packageJson = JSON.parse(readDesktopFile('package.json')) as { devDependencies?: Record<string, string> }

    for (const file of [
      'runtimeHost.ts',
      'desktopPowerLifecycle.ts',
      'productExperience.ts',
      'conversationPolicy.ts',
      'contextUsageRecovery.ts',
      'desktopTypes.ts',
      'historyRewrite.ts',
      'runtimeTransitionPolicy.ts',
      'taskTitleGenerator.ts',
      'taskTitleApplyGate.ts',
      'pathContainment.js',
    ]) {
      expect(builder).toContain(`- ${file}`)
    }
    expect(builder).toContain('- systems/**/*.ts')
    expect(builder).toContain('electronDist: ../../node_modules/electron/dist')
    expect(packageJson.devDependencies?.electron).toBe('41.10.6')
  })

  it('keeps the Electron boundary isolated', () => {
    const main = readDesktopFile('main.mjs')
    const builder = readDesktopFile('electron-builder.yml')
    const renderer = readFileSync(new URL('./renderer/index.html', import.meta.url), 'utf8')

    expect(main).toContain('contextIsolation: true')
    expect(main).toContain('nodeIntegration: false')
    expect(main).toContain('sandbox: true')
    expect(main).toContain('app.requestSingleInstanceLock()')
    expect(main).toContain("app.on('second-instance'")
    expect(main).toContain('installDesktopPowerLifecycle(powerMonitor')
    expect(main).toContain('runtimeHost?.suspendForSystemSleep()')
    expect(main).toContain('await host?.resumeAfterSystemSleep()')
    expect(main).toContain('const resumeEpoch = ++desktopPowerLifecycleEpoch')
    expect(main).toContain('if (desktopPowerSuspended || desktopPowerLifecycleEpoch !== resumeEpoch) return')
    const powerLifecycle = main.slice(
      main.indexOf('installDesktopPowerLifecycle(powerMonitor'),
      main.indexOf('  createWindow()', main.indexOf('installDesktopPowerLifecycle(powerMonitor')),
    )
    expect(powerLifecycle).not.toContain('mainWindow.show()')
    expect(powerLifecycle).not.toContain('mainWindow.focus()')
    expect(powerLifecycle).not.toContain('createWindow()')
    const secondaryInstance = main.slice(
      main.indexOf("app.on('second-instance'"),
      main.indexOf('app.whenReady()'),
    )
    expect(secondaryInstance).toContain('if (mainWindow.isMinimized()) mainWindow.restore()')
    expect(secondaryInstance).toContain('mainWindow.show()')
    expect(secondaryInstance).toContain('mainWindow.focus()')
    expect(main).toContain('if (app.isPackaged) await getRemoteHostManager()')
    expect(main).toContain('webSecurity: true')
    expect(main).toContain('allowRunningInsecureContent: false')
    expect(main).toContain('webviewTag: false')
    expect(main).toContain("mainWindow.webContents.on('will-navigate'")
    expect(main).toContain("mainWindow.webContents.on('will-redirect'")
    expect(main).toContain("mainWindow.webContents.on('will-attach-webview'")
    expect(main).toContain('mainWindow.webContents.setWindowOpenHandler')
    expect(main).toContain('mainWindow.webContents.session.setPermissionRequestHandler')
    expect(main).toContain('assertTrustedIpcSender(event)')
    expect(main).toContain("event.sender !== mainWindow.webContents")
    expect(main).toContain("actual.protocol === 'file:' && fileURLToPath(actual) === rendererEntryPath")
    expect(main).toContain("join(process.resourcesPath, 'renderer', 'turboflux-app-icon.png')")
    expect(main).not.toContain('turboflux-mark-VUo_7eDU.png')
    expect(builder).toContain('from: build/turboflux-app-icon.png')
    expect(builder).toContain('to: renderer/turboflux-app-icon.png')
    expect(main).not.toContain('requireProductAccess: true')
    expect(main).toContain('assertRuntimeResetAllowed()')
    expect(main).toContain('runtimeHost.transitionBlocker()')
    expect(main).not.toContain('externalTransitionBlocker:')
    const runtimeHostInitialization = main.slice(
      main.indexOf('async function getRuntimeHost()'),
      main.indexOf('async function startNewConversation()'),
    )
    expect(runtimeHostInitialization.indexOf('reconcileConversationSystems(snapshot)')).toBeLessThan(
      runtimeHostInitialization.indexOf('runtimeHost = host'),
    )
    expect(main).toContain("label: '文件'")
    expect(main).toContain("label: '新建对话', accelerator: 'CmdOrCtrl+N'")
    expect(main).toContain("label: '打开文件夹…', accelerator: 'CmdOrCtrl+O'")
    expect(main).toContain("role: 'close', label: '关闭窗口'")
    expect(main).toContain("unscopedWorkspacePath: unscopedWorkspacePath()")
    expect(main).toContain('const browserSystems = new Map()')
    expect(main).toContain('const computerSystems = new Map()')
    expect(main).toContain('systems.browser.register(client)')
    expect(main).toContain('systems.computer.register(client)')
    expect(main).toContain('browserSystems.get(conversationId)?.pauseForRuntime()')
    expect(main).toContain('computerSystems.get(conversationId)?.pauseForRuntime()')
    expect(main).toContain('computerLeaseOwnerId')
    expect(main).toContain("mainWindow.webContents.send('desktop:runtime-event', event)")
    expect(main).toContain("notification.once('failed'")
    expect(main).not.toContain("window.webContents.send('desktop:runtime-event', event)")
    expect(renderer).toContain('Content-Security-Policy')
    expect(renderer).toContain("script-src 'self'")
    expect(renderer).not.toMatch(/<script>(?:.|\n)*<\/script>/)
    expect(renderer).toContain('<script type="module" src="./themeBootstrap.ts"></script>')
  })

  it('serializes desktop dev restarts around the real Electron process', () => {
    const launcher = readFileSync(new URL('../../scripts/desktop-dev.mjs', import.meta.url), 'utf8')
    const main = readDesktopFile('main.mjs')

    expect(launcher).toContain("const electronBinary = desktopRequire('electron')")
    expect(launcher).toContain('acquireDevLock()')
    expect(launcher).toContain('restartSequence = restartSequence.then(async () => {')
    expect(launcher.indexOf('await stopElectron(previousElectron)')).toBeLessThan(launcher.indexOf('if (!shuttingDown) startElectron()'))
    expect(launcher).toContain("child.kill('SIGTERM')")
    expect(launcher).toContain("child.kill('SIGKILL')")
    expect(launcher).toContain("process.platform === 'darwin' ? ['--use-mock-keychain'] : []")
    expect(main).toContain('if (!safeStorage.isEncryptionAvailable()) return undefined')
    expect(main).not.toContain('if (devUrl) return undefined')
  })

  it('exposes only the intended preload operations', () => {
    const preload = readDesktopFile('preload.cjs')

    expect(preload).toContain("getSnapshot: () => ipcRenderer.invoke('desktop:get-snapshot')")
    expect(preload).toContain("getSettings: forceModels => ipcRenderer.invoke('desktop:get-settings', forceModels)")
    expect(preload).toContain("previewSettingsModels: update => ipcRenderer.invoke('desktop:preview-settings-models', update)")
    expect(preload).toContain("saveSettings: update => ipcRenderer.invoke('desktop:save-settings', update)")
    expect(preload).toContain("getBackgroundMedia: () => ipcRenderer.invoke('desktop:get-background-media')")
    expect(preload).toContain("chooseBackgroundMedia: () => ipcRenderer.invoke('desktop:choose-background-media')")
    expect(preload).toContain("removeBackgroundMedia: () => ipcRenderer.invoke('desktop:remove-background-media')")
    expect(preload).toContain("setWindowOpacity: opacity => ipcRenderer.invoke('desktop:set-window-opacity', opacity)")
    expect(preload).toContain("listCommands: () => ipcRenderer.invoke('desktop:list-commands')")
    expect(preload).not.toContain('desktop:list-skill-marketplace')
    expect(preload).not.toContain('desktop:install-marketplace-skill')
    expect(preload).not.toContain('desktop:uninstall-marketplace-skill')
    expect(preload).toContain("listWorkPacks: () => ipcRenderer.invoke('desktop:list-work-packs')")
    expect(preload).toContain("refreshWorkPacks: () => ipcRenderer.invoke('desktop:refresh-work-packs')")
    expect(preload).toContain("installLocalPlugin: () => ipcRenderer.invoke('desktop:install-local-plugin')")
    expect(preload).not.toContain('desktop:install-work-pack')
    expect(preload).not.toContain('desktop:cancel-work-pack-install')
    expect(preload).toContain("setWorkPackEnabled: (workPackId, enabled) => ipcRenderer.invoke('desktop:set-work-pack-enabled', workPackId, enabled)")
    expect(preload).toContain("uninstallWorkPack: workPackId => ipcRenderer.invoke('desktop:uninstall-work-pack', workPackId)")
    expect(preload).toContain("executeCommand: command => ipcRenderer.invoke('desktop:execute-command', command)")
    expect(preload).toContain("submitPrompt: (prompt, attachments, capabilities) => ipcRenderer.invoke('desktop:submit-prompt', prompt, attachments, capabilities)")
    expect(preload).toContain("resendFromTurn: (turnId, prompt) => ipcRenderer.invoke('desktop:resend-from-turn', turnId, prompt)")
    expect(preload).toContain("terminalList: () => ipcRenderer.invoke('desktop:terminal-list')")
    expect(preload).toContain("terminalCreate: dimensions => ipcRenderer.invoke('desktop:terminal-create', dimensions)")
    expect(preload).toContain("terminalRead: (sessionId, sinceSeq) => ipcRenderer.invoke('desktop:terminal-read', sessionId, sinceSeq)")
    expect(preload).toContain("terminalWrite: (sessionId, data) => ipcRenderer.invoke('desktop:terminal-write', sessionId, data)")
    expect(preload).toContain("terminalResize: (sessionId, cols, rows) => ipcRenderer.invoke('desktop:terminal-resize', sessionId, cols, rows)")
    expect(preload).toContain("terminalClose: sessionId => ipcRenderer.invoke('desktop:terminal-close', sessionId)")
    expect(preload).toContain("ipcRenderer.on('desktop:terminal-event', handler)")
    expect(preload).toContain("openExternal: url => ipcRenderer.invoke('desktop:open-external', url)")
    expect(preload).toContain("browserShow: () => ipcRenderer.invoke('desktop:browser-show')")
    expect(preload).toContain("browserSetBounds: bounds => ipcRenderer.invoke('desktop:browser-set-bounds', bounds)")
    expect(preload).toContain("ipcRenderer.on('desktop:browser-event', handler)")
    expect(preload).toContain("stop: () => ipcRenderer.invoke('desktop:stop')")
    expect(preload).toContain("resolveRequest: (requestId, response) => ipcRenderer.invoke('desktop:resolve-request', requestId, response)")
    expect(preload).toContain("newConversation: () => ipcRenderer.invoke('desktop:new-conversation')")
    expect(preload).toContain("newConversationInProject: id => ipcRenderer.invoke('desktop:new-project-conversation', id)")
    expect(preload).toContain("renameConversation: (id, title) => ipcRenderer.invoke('desktop:rename-conversation', id, title)")
    expect(preload).not.toContain('desktop:read-subagent')
    expect(preload).not.toContain('desktop:stop-subagent')
    expect(preload).not.toContain('desktop:retry-subagent')
    expect(preload).toContain("controlWorkStep: (taskId, action) => ipcRenderer.invoke('desktop:control-work-step', taskId, action)")
    expect(preload).toContain("gitStage: paths => ipcRenderer.invoke('desktop:git-stage', paths)")
    expect(preload).toContain("gitUnstage: paths => ipcRenderer.invoke('desktop:git-unstage', paths)")
    expect(preload).toContain("gitCommit: (message, paths) => ipcRenderer.invoke('desktop:git-commit', message, paths)")
    expect(preload).toContain("gitPush: (remote, branch, setUpstream) => ipcRenderer.invoke('desktop:git-push', remote, branch, setUpstream)")
    expect(preload).toContain("runAutomation: id => ipcRenderer.invoke('desktop:run-automation', id)")
    expect(preload).toContain("previewAutomationSchedule: (schedule, timezone, count) => ipcRenderer.invoke('desktop:preview-automation-schedule', schedule, timezone, count)")
    expect(preload).toContain("testAutomation: id => ipcRenderer.invoke('desktop:test-automation', id)")
    expect(preload).toContain("retryAutomationRun: (id, runId) => ipcRenderer.invoke('desktop:retry-automation-run', id, runId)")
    expect(preload).toContain("recoverAutomationRun: (runId, action) => ipcRenderer.invoke('desktop:recover-automation-run', runId, action)")
    expect(preload).toContain("abandonAutomationRunRecovery: runId => ipcRenderer.invoke('desktop:abandon-automation-run-recovery', runId)")
    expect(preload).toContain("cancelAutomationRun: id => ipcRenderer.invoke('desktop:cancel-automation-run', id)")
    expect(preload).toContain("saveAutomationDraft: input => ipcRenderer.invoke('desktop:save-automation-draft', input)")
    expect(preload).toContain("resetAutomationContinuationConversation: (id, expectedRevision) => ipcRenderer.invoke('desktop:reset-automation-continuation-conversation', id, expectedRevision)")
    expect(preload).toContain("setAutomationRunPinned: (runId, pinned) => ipcRenderer.invoke('desktop:set-automation-run-pinned', runId, pinned)")
    expect(preload).toContain("resolveAutomationApproval: (approvalId, response) => ipcRenderer.invoke('desktop:resolve-automation-approval', approvalId, response)")
    expect(preload).toContain("computerRelaunch: () => ipcRenderer.invoke('desktop:computer-relaunch')")
    expect(preload).toContain("importFiles: paths => ipcRenderer.invoke('desktop:import-files', paths)")
    expect(preload).toContain("importClipboardImage: (base64, mime, filename) => ipcRenderer.invoke('desktop:import-clipboard-image', base64, mime, filename)")
    expect(preload).toContain("previewArtifact: (id, purpose = 'full') => ipcRenderer.invoke('desktop:preview-artifact', id, purpose)")
    expect(preload).toContain("previewImageAttachment: (path, purpose = 'full') => ipcRenderer.invoke('desktop:preview-image-attachment', path, purpose)")
    expect(preload).toContain("exportImageAttachment: path => ipcRenderer.invoke('desktop:export-image-attachment', path)")
    expect(preload).not.toContain('desktop:install-plugin')
    expect(preload).not.toContain('desktop:set-plugin-enabled')
    expect(preload).toContain("chooseWorkspace: () => ipcRenderer.invoke('desktop:choose-workspace')")
    expect(preload).toContain("ipcRenderer.on('desktop:runtime-event', handler)")
    expect(preload).not.toContain('ipcRenderer.send(')
  })

  it('provides desktop-native composer and settings interactions', () => {
    const rendererEntry = readDesktopFile('renderer/main.ts')
    const renderer = readDesktopFile('renderer/workbench.ts')
    const taskFlowProjection = readDesktopFile('renderer/taskFlowProjection.ts')
    const rendererKernel = readFileSync(new URL('../../packages/presentation/src/index.ts', import.meta.url), 'utf8')
    const conversationPolicy = readDesktopFile('conversationPolicy.ts')
    const linearTaskFlow = readFileSync(new URL('../../packages/renderer/src/linearTaskFlow.ts', import.meta.url), 'utf8')
    const workExecutionPresentation = readDesktopFile('renderer/workExecutionPresentation.ts')
    const imageLightbox = readDesktopFile('renderer/imageLightbox.ts')
    const visualEvidence = readDesktopFile('renderer/visualEvidence.ts')
    const settings = readDesktopFile('renderer/settingsCenter.ts')
    const apiSettings = readDesktopFile('renderer/apiSettings.ts')
    const computer = readDesktopFile('renderer/computerControls.ts')
    const styles = readDesktopFile('renderer/styles.css')

    expect(renderer).toContain("event.key === 'Enter' && !event.shiftKey && !event.isComposing")
    expect(renderer).toContain('M21 3 10.6 13.4')
    expect(renderer).toContain('id="terminal-toggle"')
    expect(renderer).toContain('id="terminal-panel"')
    expect(renderer).toContain('createTerminalPanel(')
    expect(renderer).not.toContain('id="runtime-toggle"')
    expect(renderer).toContain("event.key.toLowerCase() === 'j'")
    expect(renderer).toContain("createSettingsCenter(app, bridge")
    expect(renderer).not.toContain("createAccountCenter(app, bridge")
    expect(settings).not.toContain('TurboFlux 官方托管模型与自己的 API 可以同时保留')
    expect(settings).toContain('handleSettingsUpdate')
    expect(styles).toContain('.markdown-body ol { padding-left: 2.45em; }')
    expect(styles).toContain('--content-block-gap: 8px')
    expect(styles).toContain('--flow-row-height: 25px')
    expect(styles).toContain('.linear-task-flow > .linear-flow-item[data-flow-gap="content"] { margin-top: var(--content-block-gap); }')
    expect(styles).toContain('.linear-task-flow .message-row.assistant .markdown-body > * { margin-top: 0; margin-bottom: 0; }')
    expect(styles).toContain('.linear-disclosure:not(.expanded) > .linear-disclosure-body > .linear-disclosure-body-inner')
    expect(styles).toContain('.linear-task-flow .message-row.assistant .markdown-body code:not(pre code) { padding-top: 0; padding-bottom: 0;')
    expect(styles).not.toContain('.execution-group')
    expect(renderer).toContain('renderedConversationSignature')
    expect(renderer).toContain('function handleConversationEvent(event: AnyConversationEvent)')
    expect(renderer).toContain('const turn = event.payload.turn')
    const canonicalHandler = renderer.slice(
      renderer.indexOf('function handleConversationEvent(event: AnyConversationEvent)'),
      renderer.indexOf('function handleRuntimeEvent(event: WorkbenchEvent)'),
    )
    expect(canonicalHandler).not.toContain('appendTurn(')
    expect(canonicalHandler).not.toContain('appendStream(')
    expect(canonicalHandler).not.toContain('appendThinking(')
    expect(canonicalHandler).not.toContain('startStream(')
    expect(canonicalHandler).not.toContain('finishStreams(')
    expect(renderer).not.toContain('startRequestStatus(')
    expect(renderer).not.toContain('request-progress')
    expect(renderer).not.toContain('assistant-signature')
    expect(renderer).toContain('hasRenderableTurnPayload({')
    expect(renderer).toContain('createLinearTaskFlowRenderer(transcript, {')
    expect(renderer).toContain('renderCanonicalTaskFlow(true)')
    expect(renderer).not.toContain("round.className = 'execution-round'")
    expect(renderer).not.toContain('继续处理')
    expect(renderer).not.toContain('function startStream()')
    expect(renderer).not.toContain('function appendStream(')
    expect(renderer).not.toContain('function appendThinking(')
    expect(renderer).not.toContain('liveToolRounds')
    expect(renderer).toContain('resolveTool: node => {')
    expect(renderer).not.toContain('if (!activeTurnIsTask) return')
    expect(renderer).not.toContain("thinkingElement.dataset.userExpanded = 'false'")
    expect(renderer).not.toContain("block.dataset.userExpanded = 'false'")
    expect(renderer).not.toContain('function appendExecutionTurn(')
    expect(renderer).not.toContain('adoptLiveExecutionContent(')
    expect(renderer).not.toContain('applyExecutionStepVisibility(')
    expect(renderer).not.toContain('shouldFinalizeAssistantTurnInTask(')
    expect(renderer).toContain("case 'run.completed':")
    expect(renderer).toContain('refreshConversationSystemSnapshots()')
    expect(renderer).toContain("event.type === 'conversation-run'")
    expect(renderer).toContain("event.type === 'conversation-event'")
    expect(renderer).toContain("event.type === 'settings-updated'")
    expect(renderer).not.toContain("event.type === 'flow-event'")
    expect(renderer).not.toContain("event.type === 'work-event'")
    expect(renderer).not.toContain("event.type === 'agent'")
    expect(renderer).toContain('applyConversationViewEvent(previousView, event.event)')
    expect(taskFlowProjection).toContain("from '@turboflux/presentation'")
    expect(taskFlowProjection).not.toContain("export * from '@turboflux/workbench'")
    expect(rendererKernel).toContain("export * from './taskFlowProjection'")
    expect(rendererKernel).toContain("export * from '@turboflux/contracts/workExecutionTypes'")
    expect(rendererKernel).toContain("export { generatedConversationTitle } from './conversationTitle'")
    expect(conversationPolicy).toContain("from '@turboflux/presentation'")
    expect(conversationPolicy).not.toContain("from '@turboflux/workbench'")
    expect(linearTaskFlow).toContain("from '@turboflux/presentation'")
    expect(linearTaskFlow).not.toContain("from '@turboflux/workbench'")
    expect(workExecutionPresentation).toContain("export * from '@turboflux/presentation'")
    expect(workExecutionPresentation).not.toContain("export * from '@turboflux/workbench'")
    expect(renderer).toContain("renderer.schedule('transcript'")
    expect(renderer).toContain('transcriptIndex.setTurn(turn)')
    expect(renderer).toContain("element.classList.add('optimistic-user-turn')")
    expect(renderer).toContain('reconcileOptimisticUserTurn(turn)')
    expect(renderer).toContain('scheduleCanonicalTaskFlowRender()')
    expect(renderer).toContain('applyConversationViewEvent(previousView, event.event)')
    expect(renderer).not.toContain('showTaskCompletionBanner')
    expect(renderer).not.toContain('createTaskDurationLabel')
    expect(renderer).toContain('snapshotRefreshInFlight')
    expect(renderer).toContain('createCommandPalette(app, bridge')
    expect(renderer).not.toContain('createWorkOverviewSection')
    expect(renderer).not.toContain('renderWorkOverview')
    expect(renderer).toContain("'danger-full-access': '完整访问'")
    expect(renderer).not.toContain('任务、Agent 与 Flow')
    expect(renderer).toContain("value.startsWith('/')")
    expect(renderer).not.toContain('id="mode-switch"')
    expect(renderer).toContain('id="composer-add"')
    expect(renderer).toContain('class="sidebar-nav-item work-packs-entry" data-view="skills"')
    expect(renderer).toContain('class="sidebar-nav-item automation-entry" data-view="automations"')
    expect(renderer).toContain('newConversation: SquarePen')
    expect(renderer).not.toContain("automationNav: '<svg")
    expect(renderer).toContain('pluginNav: Puzzle')
    expect(renderer).toContain('id="settings-button" title="设置"')
    expect(renderer).not.toContain('id="workspace-picker"')
    expect(renderer).not.toContain('<small>当前工作区</small>')
    expect(renderer).toContain('id="composer-start-workspace-name">选择工作区</span>')
    expect(renderer).not.toContain('avatar.textContent = displayName.slice(0, 1)')
    expect(renderer).not.toContain("querySelector<HTMLElement>('#sidebar-panel-avatar')!.textContent")
    expect(renderer).toContain('id="welcome-profile-avatar"')
    expect(renderer).toContain('id="welcome-greeting"')
    expect(renderer).toContain('id="welcome-workspace-prompt"')
    expect(renderer).not.toContain('workbench-title-brand')
    expect(renderer).not.toContain('startProductTitleTypewriter')
    expect(styles).toContain('--composer-rail: 640px;')
    expect(styles).toContain('.welcome-block { width: min(100%, 680px);')
    expect(styles).toContain('font-size: clamp(30px,2.4vw,36px)')
    expect(styles).toContain('.composer-stack { --composer-radius: 18px;')
    expect(styles).toContain('margin: 22px auto 0;')
    expect(styles).toContain('width: calc(100% - 28px); max-height: 48px;')
    expect(styles).toContain('padding: 12px 14px 10px;')
    expect(styles).toContain('min-height: 38px; margin: 0 0 6px;')
    expect(renderer).not.toContain('id="home-conversation-list"')
    expect(renderer).not.toContain('未命名任务')
    expect(renderer).toContain('Number.MAX_SAFE_INTEGER')
    expect(renderer).toContain('projectWorkspaceConversationGroups({')
    expect(renderer).toContain("workspaceGroupExpansionStorageKey = 'turboflux.workspace-groups.expansion'")
    expect(renderer).toContain('bridge.newConversationInProject(group.projectId!)')
    expect(renderer).not.toContain('今天想完成什么工作？')
    expect(styles).toContain('.workbench-prompt-title')
    expect(renderer).not.toContain('class="quick-card"')
    expect(renderer).not.toContain('composer-start-guidance')
    expect(renderer).not.toContain('研究资料并整理清晰结论')
    expect(renderer).not.toContain('class="composer-rail"')
    expect(renderer).not.toContain('id="browser-workspace"')
    expect(renderer).not.toContain('id="inspector-overview-back"')
    expect(renderer).toContain('? { x: 0, y: 0, width: 0, height: 0 }')
    expect(renderer).toContain("type InspectorTab = 'activity' | 'outputs' | 'browser' | 'context' | 'git'")
    expect(renderer).not.toContain("{ tab: 'activity', label: '任务', iconName: 'activity' }")
    expect(renderer).not.toContain("{ tab: 'outputs', label: '产物', iconName: 'outputs' }")
    expect(renderer).toContain('function renderInspectorLanding()')
    expect(renderer).toContain('data-inspector-entry="browser"')
    expect(renderer).not.toContain("{ tab: 'overview', label: '概览'")
    expect(renderer).toContain('id="inspector-tabs" role="tablist"')
    expect(renderer).toContain('id="inspector-module-menu" role="menu"')
    expect(renderer).toContain('else showInspectorLanding()')
    expect(renderer).not.toContain('BrowserDisplayMode')
    expect(renderer).not.toContain('browserDisplayMode')
    expect(renderer).not.toContain('function inspectorLandingTab()')
    expect(renderer).toContain('const activeTab = activeInspectorPanelTab()')
    expect(renderer).toContain("button.addEventListener('click', () => void openBrowserInInspector(view.previewUrl!))")
    expect(renderer).not.toContain('task-companion')
    expect(renderer).toContain('id="work-plan-dock"')
    expect(renderer.match(/id="inspector-toggle"/g) ?? []).toHaveLength(1)
    expect(renderer).toContain('class="icon-button work-drawer-toggle" id="inspector-toggle"')
    expect(renderer.indexOf('</main>')).toBeLessThan(renderer.indexOf('id="inspector-toggle"'))
    expect(renderer).not.toContain('id="inspector-close"')
    expect(renderer).toContain('onOpenBrowser: isBuiltInBrowserTool(call.name)')
    expect(renderer).toContain('function openBrowserExecution(toolCallId: string)')
    expect(linearTaskFlow).toContain('onOpenBrowser?: () => void')
    expect(linearTaskFlow).toContain('onOpenBrowser: tool.onOpenBrowser')
    expect(linearTaskFlow).not.toContain('tool.onOpenBrowser?.()')
    expect(linearTaskFlow).not.toContain('options.resolveTool(item.nodes.at(-1)!).onOpenBrowser?.()')
    expect(readFileSync(new URL('../../packages/renderer/src/toolResultView.ts', import.meta.url), 'utf8')).toContain('button.onclick = options.onOpenBrowser')
    const browserStateRenderer = renderer.slice(renderer.indexOf('function renderBrowserSnapshot'), renderer.indexOf('async function refreshConversationSystemSnapshots'))
    expect(browserStateRenderer).toContain("openInspector('browser')")
    expect(browserStateRenderer).toContain('agentToolCallId !== lastAutoOpenedBrowserToolCallId')
    expect(browserStateRenderer).toContain('syncInspectorBrowserTabs(snapshot)')
    expect(renderer).toContain('function updateInspectorBrowser(snapshot: BrowserSystemSnapshot): boolean')
    expect(browserStateRenderer).toContain("if (activeInspectorPanelTab()?.kind !== 'browser' || !updateInspectorBrowser(snapshot)) renderInspector()")
    expect(browserStateRenderer).not.toContain("currentInspectorTab === 'browser' && !inspectorAddressFocused")
    expect(renderer).not.toContain('renderBrowserTabs(inspectorTabs, true)')
    expect(renderer).toContain("addressForm.className = 'inspector-browser-address-form'")
    expect(renderer).not.toContain("expand.title = '在工作区展开'")
    expect(renderer).toContain("inspectorBrowserNewTab.addEventListener('click'")
    expect(renderer).toContain("(event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 't' && browserSnapshot?.visible")
    expect(renderer).toContain("inspectorContent.querySelector<HTMLInputElement>('.inspector-browser-address')")
    expect(renderer).not.toContain('Agent 浏览器')
    expect(renderer).toContain('bridge.browserSetBounds')
    expect(renderer).toContain('? { x: 0, y: 0, width: 0, height: 0 }')
    expect(styles).toContain('.inspector-browser-surface')
    expect(styles).not.toContain('.inspector-browser-tabs')
    expect(styles).not.toContain('.inspector-browser-tabbar')
    expect(styles).toContain('.browser-activity-pill[hidden]')
    expect(renderer).toContain('id="approval-pill"')
    expect(renderer).toContain("title: '添加文件'")
    expect(renderer).toContain("title: '选择技能'")
    expect(renderer).toContain('function renderSkillMenu()')
    expect(renderer).toContain('snapshot.skills.filter(')
    expect(renderer).not.toContain('id="capability-tab"')
    expect(renderer).not.toContain('function renderCapabilityMenu()')
    expect(renderer).toContain('aria-keyshortcuts="Shift+Tab"')
    expect(renderer).toContain('const submittedCapabilities = draftCapabilities.length > 0')
    expect(renderer).toContain('submittedCapabilities,')
    expect(renderer).toContain("capability.id === 'computer'")
    expect(renderer).not.toContain('conversation-plugins-toggle')
    expect(renderer).not.toContain('function renderConversationPluginsMenu()')
    expect(renderer).toContain('let pendingConversationRender = false')
    expect(renderer).toContain('if (editingTurnId && !conversationChanged)')
    expect(renderer).toContain('captureTranscriptViewportAnchor()')
    expect(renderer).toContain('const composerActionGuard = new SingleFlightGuard()')
    expect(renderer).toContain('const resendGuard = new SingleFlightGuard()')
    expect(renderer).toContain('draftRecordQueue.enqueue(() => bridge.recordDraft(draft))')
    expect(renderer).toContain('composerActionGuard.active || conversationNavigationGuard.active')
    expect(renderer).toContain("overlay.className = 'workflow-surface-inline'")
    expect(renderer).toContain("transcriptMutationObserver.observe(transcript, { childList: true })")
    expect(renderer).not.toContain('subtree: true, characterData: true')
    expect(renderer).toContain("if (action === 'pause') await bridge.pause()")
    expect(renderer).toContain("else await bridge.resume()")
    expect(renderer).not.toContain("if (currentSnapshot?.runtime.status === 'running') await bridge.stop()")
    expect(renderer).toContain("'turboflux.inspector.right-panel-width:v3'")
    expect(renderer).toContain("inspectorResizeHandle.addEventListener('pointerdown'")
    expect(renderer).toContain("inspectorResizeHandle.addEventListener('keydown'")
    expect(renderer).toContain('inspectorWidthFromKey(')
    expect(renderer).toContain("aria-keyshortcuts=\"ArrowLeft ArrowRight Home End\"")
    expect(styles).toMatch(/\.inspector-resize-handle \{[^}]*width: 16px/)
    expect(styles).toContain('.inspector-resize-handle:focus-visible::before')
    expect(styles).toContain('--conversation-content-rail: calc(var(--content-rail) - (2 * var(--transcript-inline-padding)))')
    expect(styles).toContain('width: min(calc(100% - (2 * var(--transcript-inline-padding))), var(--conversation-content-rail))')
    expect(styles).toMatch(/\.conversation-mode \.transcript\.linear-task-flow \{[^}]*width: min\(100%, var\(--content-rail\)\)/)
    expect(styles).not.toContain('width: min(100%, 748px)')
    expect(styles).toMatch(/\.transcript \{[^}]*scrollbar-gutter: auto/)
    expect(styles).not.toMatch(/\.message-row\.user \.message-content \{[^}]*margin-right/)
    expect(styles).not.toContain('.desktop-shell.inspector-open .main-panel { margin-right: var(--work-panel-width); }')
    expect(styles).toContain('.workbench-window-actions { position: absolute; z-index: 170; top: 0; right: var(--window-actions-right);')
    expect(styles).not.toContain('.desktop-shell.inspector-open .conversation-mode .transcript')
    expect(styles).toContain('.inspector { position: relative; z-index: 150; width: 0;')
    expect(styles).toContain('container-type: inline-size')
    expect(renderer).toContain('inspectorDismissTriggerX(')
    expect(renderer).toContain('shouldDismissInspectorAtPointer(')
    expect(renderer).not.toContain('closeInspector(true)')
    expect(renderer).toContain("lifetime.listen(window, 'pointerup', finish)")
    expect(styles).toContain('.linear-turn-status::after')
    expect(styles).not.toContain('.request-progress')
    expect(styles).not.toContain('.assistant-signature')
    expect(styles).toMatch(/\.image-lightbox \{[^}]*background: transparent;/)
    expect(styles).not.toContain('max-height: 1600px')
    expect(renderer).toContain('await persistDraftNow()')
    expect(settings).toContain("{ id: 'computer', title: '电脑操控'")
    expect(computer).toContain("button.textContent = '原生申请'")
    expect(computer).toContain("'开始原生引导'")
    expect(computer).toContain("'继续原生引导'")
    expect(computer).toContain("result.outcome === 'cancelled'")
    expect(renderer).toContain("event.clipboardData?.getData('text/plain')")
    expect(renderer).toContain('bridge.pathForFile(file)')
    expect(settings).toContain("bridge.getSettings(force)")
    expect(apiSettings).toContain('bridge.previewSettingsModels(structuredClone({ ...draft, activeApiConfigId: profile.id }))')
    expect(settings).not.toContain('ensureSettings(true)')
    expect(settings).toContain("bridge.saveSettings(draft)")
    expect(apiSettings).toContain('saved?.apiKeyPreview')
    expect(apiSettings).toContain('更换密钥')
    const localExtensions = readDesktopFile('renderer/localExtensionsView.ts')
    expect(settings).toContain('renderLocalExtensions(content,')
    expect(localExtensions).toContain('从本地安装')
    expect(localExtensions).toContain("toggle.type = 'checkbox'")
    expect(localExtensions).toContain('selected.canUninstall')
    expect(settings).not.toContain('skill-install-track')
    expect(settings).not.toContain('class="official-market"')
    expect(styles).not.toContain('.official-market')
    expect(settings).not.toContain('TurboFlux Official')
    expect(settings).not.toContain('<span>TurboFlux 官方能力</span>')
        expect(settings).not.toContain('整幅推荐图待接入')
    expect(settings).not.toContain('整幅产品展示图待接入')
    expect(settings).not.toContain('official-pack-showcase')
    expect(localExtensions).toContain("from 'lucide'")
    expect(styles).toContain('.local-extension-row')
    expect(settings).not.toContain('official-feature-art')
    expect(settings).not.toContain('official-pack-showcase-visual')
    expect(localExtensions).toContain('搜索本地插件')
    expect(settings).not.toContain('查看来源 ↗')
    expect(settings).not.toContain('导入 SKILL.md')
    expect(settings).not.toContain('Skills 目录')
    expect(settings).not.toContain('bridge.listSkillMarketplace()')
    expect(settings).not.toContain('bridge.installMarketplaceSkill(')
    expect(settings).not.toContain('bridge.uninstallMarketplaceSkill(')
    expect(renderer).not.toContain('onUseSkill: async skillId =>')
    expect(renderer).toContain('onUseCapability: async capability =>')
    expect(renderer).not.toContain('taskInput.value = promptTemplate')
    expect(settings).not.toContain('options.onUseSkill')
    const picker = settings.slice(settings.indexOf('async function openModelPicker'), settings.indexOf("overlay.querySelector('#settings-back')"))
    expect(picker).toContain('正在读取模型…')
    expect(picker.indexOf("popover.classList.add('visible')")).toBeLessThan(picker.indexOf('await ensureSettings()'))
    expect(picker).toContain("if (!popover.classList.contains('visible')) return")
    expect(settings).toContain("popover.classList.remove('submenu-left')")
    expect(settings).toContain('anchoredComposerPopoverPosition(')
    expect(settings).toContain("options.getComposerPopoverPlacement?.() || 'above'")
    expect(settings).toContain('popover.dataset.placement = position.placement')
    expect(settings).toContain("popover.className = 'model-popover model-only-popover'")
    expect(settings).toContain("popover.className = 'model-popover reasoning-popover'")
    expect(settings).toContain('id="reasoning-slider" type="range"')
    expect(settings).toContain('step="0.001"')
    expect(settings).toContain('class="reasoning-slider-marks"')
    expect(settings).toContain('class="reasoning-slider-thumb"')
    expect(settings).toContain('data-reasoning-tone="${active.tone}"')
    expect(settings).toContain('id="reasoning-choice-default"')
    expect(settings).not.toContain('class="reasoning-segments"')
    expect(settings).toContain('persistQuickChange({ keepPickerOpen: true, applySnapshot: false })')
    expect(settings).toContain("slider.addEventListener('input', () => {")
    expect(settings).toContain('preview(Number(slider.value), selectNearestOnInput || !dragging)')
    expect(settings).toContain("slider.addEventListener('keydown', event => {")
    expect(settings).toContain("slider.addEventListener('pointerdown'")
    expect(settings).toContain("event.key === 'ArrowRight'")
    expect(settings).toContain("event.key === 'Home'")
    expect(settings).toContain("event.key === 'End'")
    expect(settings).toContain("reasoningName.textContent = option.label")
    expect(settings).toContain('latestReasoningIndex = index')
    expect(settings).toContain('reasoningRevision += 1')
    expect(settings).toContain('persistedReasoningRevision < reasoningRevision')
    expect(settings).toContain('pendingProfile.reasoning = { ...pendingOption.config }')
    expect(settings).toContain('let persistFailed = false')
    expect(settings).toContain('if (!persistFailed && persistedReasoningRevision < reasoningRevision)')
    expect(settings).toContain('applySnapshot: false')
    expect(settings).toContain('}, 80)')
    expect(settings).not.toContain('let commitQueue = Promise.resolve()')
    expect(settings).toContain('if (!behavior.keepPickerOpen) hidePicker()')
    expect(settings).toContain('const currentProfile = draft ? selectedProfile(draft) : undefined')
    expect(settings).toContain("mcpServers: undefined")
    expect(settings).toContain('filter(server => !server.system)')
    expect(settings).toContain('随 TurboFlux 桌面端提供，由核心维护')
    expect(settings).toContain('class="settings-window"')
    expect(settings).toContain('id="settings-search"')
    expect(settings).toContain('settingsNavigationMarkup()')
    expect(settings.indexOf("id: 'api', title: '模型API管理'")).toBeLessThan(settings.indexOf("id: 'appearance', title: '外观'"))
    expect(styles).toContain('grid-template-columns: 264px minmax(0, 1fr)')
    expect(styles).toContain('width: 100%; height: 100%')
    expect(styles).toContain('.composer-tooltip-anchor {')
    expect(styles).toContain('.composer-add-button { display: grid; width: 30px; height: 30px;')
    expect(styles).toContain('.computer-guide-action')
    expect(styles).toContain('.reasoning-tab { width: auto; max-width: 168px; flex: 0 1 auto;')
    expect(styles).toContain('.reasoning-choice-card { position: relative; overflow: hidden;')
    expect(styles).toContain('[data-reasoning-tone="medium"]')
    expect(styles).toContain('[data-reasoning-tone="high"]')
    expect(styles).toContain('[data-reasoning-tone="xhigh"]')
    expect(styles).toContain('.reasoning-slider-marks {')
    expect(styles).toContain('.reasoning-slider-mark {')
    expect(settings).toContain('reasoningSliderDetentValue(rawValue, reasoningOptions.length, index)')
    expect(settings).toContain("card.classList.add('is-notching')")
    expect(styles).toContain('@keyframes reasoning-slider-notch')
    expect(styles).not.toContain('@keyframes reasoning-slider-surge')
    expect(styles).toContain('.reasoning-slider-thumb {')
    expect(styles).not.toContain('.reasoning-segment-selection')
    expect(styles).not.toContain('@keyframes reasoning-max-spectrum-sweep')
    expect(renderer).toContain('reasoningTab.dataset.reasoningTone = reasoningTone(snapshot.runtime.reasoning)')
    expect(renderer).not.toContain('bridge.readSubAgent(')
    expect(renderer).not.toContain('bridge.stopSubAgent(')
    expect(renderer).not.toContain('bridge.retrySubAgent(')
    expect(renderer).toContain('bridge.controlWorkStep(id, action)')
    expect(styles).not.toContain('.subagent-timeline-row')
    expect(renderer).toContain('bridge.gitStage(paths)')
    expect(renderer).toContain('bridge.gitRestore(paths)')
    expect(renderer).toContain('bridge.gitPush(remote, branch, setUpstream)')
    expect(renderer).toContain("bridge.previewArtifact(artifactId, 'thumbnail')")
    expect(renderer).toContain('bridge?.exportArtifact(artifact.id)')
    expect(renderer).toContain('refreshExecutionVisualEvidence(snapshot)')
    expect(renderer).toContain("host.className = 'execution-visual-evidence linear-flow-visual-evidence'")
    expect(styles).toContain('.visual-evidence-thumbnail')
    expect(styles).toContain('.image-lightbox')
    expect(styles).toContain('background: transparent')
    expect(styles).toContain('.draft-image-remove::before')
    expect(renderer).toContain("gallery.className = 'message-image-grid'")
    expect(renderer).toContain("card.className = 'draft-image-card'")
    expect(renderer).toContain('bridge.previewImageAttachment(path, purpose)')
    expect(imageLightbox).toContain("if (typeof image.decode === 'function') await image.decode()")
    expect(imageLightbox).not.toContain('for (const adjacent of')
    expect(visualEvidence).toContain('options.defaultCollapsed !== false')
    expect(visualEvidence).toContain('if (!collapsed) mountThumbnails()')
    expect(settings).toContain("{ id: 'workpacks', title: '插件'")
    expect(settings).toContain('bridge.listWorkPacks()')
    expect(settings).not.toContain('bridge.installWorkPack(')
    expect(settings).toContain('bridge.setWorkPackEnabled(id, enabled)')
    expect(settings).toContain('bridge.uninstallWorkPack(id)')
    expect(settings).not.toContain('bridge.installMarketplacePlugin(')
    expect(settings).not.toContain('bridge.setPluginEnabled(')
    expect(styles).toContain('.git-inline-diff')
    const browser = readDesktopFile('browser/browserSystem.ts')
    const browserTools = readDesktopFile('browser/browserTools.ts')
    expect(browserTools).toContain("name: 'upload_file'")
    expect(browser).toContain("send('DOM.setFileInputFiles'")
    expect(browser).toContain('Browser uploads must use a file inside the active workspace')
  })

  it('hosts the shared application runtime outside the renderer', () => {
    const main = readDesktopFile('main.mjs')
    const runtimeHost = readDesktopFile('runtimeHost.ts')

    expect(main).toContain("import { DesktopRuntimeHost } from './runtimeHost.ts'")
    expect(main).toContain("import { BrowserSystem } from './browser/browserSystem.ts'")
    expect(main).toContain("import { ComputerSystem } from './computer/computerSystem.ts'")
    expect(main).toContain("mainWindow.webContents.send('desktop:runtime-event', event)")
    expect(runtimeHost).toContain("from '@turboflux/workbench'")
    expect(runtimeHost).toContain('buildWorkPackCatalog({')
    expect(runtimeHost).toContain('await this.requireRuntime().installPlugin(inspected.path, approvedPermissions)')
    expect(runtimeHost).not.toContain('runtime.installMarketplacePlugin(entry.backend.marketplaceId')
    expect(runtimeHost).not.toMatch(/from ['"]\.\.?\/[^'"]*(?:application|core|shared)\//)
    expect(runtimeHost).toContain('new WorkbenchRuntime({')
    expect(runtimeHost).toContain('new AutomationCoordinator(')
    expect(runtimeHost).toContain('new AutomationRepository(')
    expect(runtimeHost).toContain('new WorkspaceRuntimePool({')
    expect(runtimeHost).toContain("automationScheduling: 'external'")
    expect(runtimeHost).toContain('return this.automationCoordinator.runManual(id)')
    expect(runtimeHost).toContain('connectMcp: true')
    expect(runtimeHost).toContain('registerSystemPlugins: this.registerSystemPlugins')
    expect(runtimeHost).toContain('await runtime.initializePlatform()')
    expect(runtimeHost).toContain("const DESKTOP_REMOVED_TOOLS = ['web_search', 'web_fetch']")
    expect(runtimeHost).toContain('runtime.runtime.engine.setDisabledTools')
    expect(runtimeHost).toContain("this.scheduleTaskTitleUpdate(snapshot.conversation.id, promptCount, result.status === 'started' ? titleApplyGate : undefined)")
    expect(runtimeHost).toContain("runtime.renameConversation(conversationId, title, 'generated')")
    expect(runtimeHost).toContain('runtimeTransitionBlocker(runtime.getSnapshot(), options)')
    expect(runtimeHost.indexOf('host.automationCoordinator.initialize()')).toBeLessThan(runtimeHost.indexOf('await host.replaceRuntime(host.workspacePath)'))
    expect(runtimeHost).toContain('const externalBlocker = this.externalTransitionBlocker?.()')
    expect(runtimeHost).toContain('this.runtime !== runtime || this.runtimeEpoch !== runtimeEpoch')
    expect(runtimeHost).toContain('stopConversation(id: string)')
    expect(runtimeHost).toContain('resumeConversation(id: string)')
    const directedControlMethod = runtimeHost.slice(runtimeHost.indexOf('  controlConversation('), runtimeHost.indexOf('  async resendFromTurn('))
    expect(directedControlMethod).toContain('this.runDirectedConversationOperation(conversationId')
    expect(directedControlMethod).toContain('runtime.pauseConversation(conversationId)')
    expect(directedControlMethod).toContain('runtime.resumeConversation(conversationId)')
    expect(directedControlMethod).toContain('runtime.stopConversation(conversationId)')
    const setWorkspaceMethod = runtimeHost.slice(runtimeHost.indexOf('  async setWorkspace('), runtimeHost.indexOf('  private decorateSnapshot('))
    expect(setWorkspaceMethod).toContain('await this.replaceRuntime(nextPath)')
    expect(runtimeHost).not.toContain('installSafeWorkPackUpdates')
    expect(runtimeHost).not.toContain('PluginMarketplaceFeedClient')
    expect(runtimeHost).toContain('automations: this.automationService.list()')
    const newConversationMethod = runtimeHost.slice(runtimeHost.indexOf('  async newConversation()'), runtimeHost.indexOf('  async switchConversation('))
    expect(newConversationMethod).not.toContain('setWorkspace(this.unscopedWorkspacePath)')
    expect(newConversationMethod).toContain('const reusable = reusableEmptyConversation(snapshot.conversations, snapshot.conversation.id)')
    expect(newConversationMethod).toContain("const hasActiveWork = snapshot.conversationRuntimes.some(conversationRuntime => conversationRuntime.status !== 'ready')")
    expect(newConversationMethod).toContain('if (hasActiveWork || !reusable)')
    expect(main).toContain('reconcileConversationSystems(snapshot)')
    expect(main).toContain("ipcMain.handle('desktop:get-host-preferences'")
    expect(main).toContain("ipcMain.handle('desktop:save-host-preferences'")
    expect(main).toContain("buttons: ['等待完成后退出', '保存并中断', '取消退出']")
    expect(main).toContain("effectiveCloseWindowBehavior(desktopHostPreferences) === 'quit'")
    expect(runtimeHost).toContain("prepareForApplicationQuit(mode: 'wait' | 'interrupt')")
    expect(main).toContain("ipcMain.handle('desktop:rollback-automation-definition'")
    expect(main).toContain("ipcMain.handle('desktop:recover-automation-run'")
    expect(main).toContain("ipcMain.handle('desktop:abandon-automation-run-recovery'")
    expect(runtimeHost).toContain('abandonAutomationRunRecovery(runId: string)')
    expect(main).toContain("ipcMain.handle('desktop:set-automation-run-pinned'")
    expect(runtimeHost).toContain('hasPlugin: id => Boolean(this.runtime?.plugins.list().plugins.find(plugin => plugin.id === id && plugin.enabled))')
    expect(main).toContain('reconcileConversationSystems(runtimeHost.getSnapshot())')
    expect(main).toContain('runtimeHostGeneration += 1')
    expect(main).toContain('await runtimeHostResetPromise')
    expect(main).toContain('host.stopConversation(runtime.conversationId)')
    expect(main).toContain('const conversationId = activeConversationId || host.getSnapshot().conversation.id')
    expect(main).toContain('const paused = host.pauseConversation(conversationId)')
    expect(runtimeHost).toContain("const paused = snapshot.runtime.status === 'paused'")
    expect(runtimeHost).toContain('runtime.submitPrompt(prompt, attachments, capabilities, { forceQueue: paused })')
    expect(readDesktopFile('conversationWorkspacePolicy.ts')).toContain('isUnboundWorkspacePath(workspacePath)')
    const switchConversationMethod = runtimeHost.slice(runtimeHost.indexOf('  private async switchConversationWithOptions('), runtimeHost.indexOf('  deleteConversation('))
    expect(switchConversationMethod).toContain('assertExecutableConversationWorkspace(target.workspacePath)')
    expect(setWorkspaceMethod).toContain('assertExecutableConversationWorkspace(initialTarget.workspacePath)')
    expect(main).toContain("await realpath(resolve(host.getSnapshot().workspace.path, '.turboflux', 'attachments'))")
    expect(main).toMatch(/desktop:browser-get-state[\s\S]*?await getRuntimeHost\(\)[\s\S]*?requireBrowserSystem\(\)\.getSnapshot\(\)/)
    expect(runtimeHost).not.toContain('if (promptCount === 1) this.scheduleTaskTitleUpdate')
    expect(runtimeHost).toContain('projects.find(project => resolve(project.path) === resolve(snapshot.workspace.path))?.name || snapshot.workspace.name')
    expect(runtimeHost).toContain(": '未指定工作区'")
  })

  it('waits for the shared runtime to persist before Electron exits', () => {
    const main = readDesktopFile('main.mjs')
    const runtimeHost = readDesktopFile('runtimeHost.ts')
    const shutdownApplication = main.slice(
      main.indexOf('async function shutdownDesktopApplication()'),
      main.indexOf('function remoteStateProtection()'),
    )
    const shutdown = main.slice(
      main.indexOf("app.on('before-quit'"),
    )

    expect(main).toContain('async function shutdownDesktopApplication()')
    expect(main).toContain('await resetRuntimeHost()')
    expect(shutdownApplication.indexOf('disposeDesktopPowerLifecycle?.()')).toBeLessThan(shutdownApplication.indexOf('await resetRuntimeHost()'))
    expect(shutdown).toContain('event.preventDefault()')
    expect(shutdown).toContain('if (shutdownPromise) return')
    expect(shutdown).toContain('shutdownComplete = true')
    expect(shutdown).toContain('app.quit()')
    expect(main).not.toContain('if (runtimeHost) void runtimeHost.destroy()')
    const runtimeShutdown = runtimeHost.slice(runtimeHost.indexOf('private async performDestroy()'), runtimeHost.indexOf('private async replaceRuntime('))
    expect(runtimeShutdown.indexOf('this.automationCoordinator.stop()')).toBeLessThan(runtimeShutdown.indexOf('this.workspaceRuntimePool.destroy()'))
    expect(runtimeShutdown.indexOf('this.workspaceRuntimePool.destroy()')).toBeLessThan(runtimeShutdown.indexOf('this.automationCoordinator.waitForIdle()'))
    const closedWindow = main.slice(main.indexOf("mainWindow.on('closed'"), main.indexOf('function requireBrowserSystem()'))
    expect(closedWindow).not.toContain('resetRuntimeHost')
    expect(main).toContain("if (effectiveCloseWindowBehavior(desktopHostPreferences) === 'quit') app.quit()")
  })

  it('registers browser artifacts and isolates plugin code', () => {
    const main = readDesktopFile('main.mjs')
    const coreWorkbenchUrl = import.meta.resolve('@turboflux/workbench')
    const coreManifest = JSON.parse(readFileSync(new URL('../package.json', coreWorkbenchUrl), 'utf8'))

    expect(main).toContain("event?.type === 'artifact-ready' && event.path")
    expect(main).toContain("const source = event.kind === 'download' ? 'browser-download' : 'browser'")
    expect(main).toContain("visualSource: 'computer'")
    expect(main).toContain("console.error('Failed to register computer visual evidence:'")
    expect(coreManifest.exports).toHaveProperty('.')
    expect(coreManifest.dependencies).toHaveProperty('@turboflux/extensions')
    expect(coreManifest.exports).not.toHaveProperty('./core/*')
    expect(coreManifest.exports).not.toHaveProperty('./application/*')
  })

  it('guides macOS Computer permissions through native dialogs and focus refresh', () => {
    const main = readDesktopFile('main.mjs')

    expect(main).toContain('const COMPUTER_PERMISSION_GUIDES = {')
    expect(main).toContain('dialog.showMessageBox(mainWindow')
    expect(main).toContain("buttons: ['继续申请', '取消']")
    expect(main).toContain("buttons: ['打开系统设置', '取消']")
    expect(main).toContain("if (kind === 'screen-recording') return app.isPackaged ? 'TurboFlux' : 'Electron'")
    expect(main).toContain("'TurboFlux 电脑辅助程序（系统也可能显示 TurboFluxComputerHelper）'")
    expect(main).toContain("outcome: 'cancelled'")
    expect(main).toContain('outcome: computerPermissionOutcome(snapshot, kind)')
    expect(main).toContain("if (status.restartRequired) return 'restart-required'")
    expect(main).toContain("ipcMain.handle('desktop:computer-relaunch'")
    expect(main).toContain("mainWindow.on('focus'")
    expect(main).toContain('computerSystem?.refresh()')
  })

  it('puts Computer approvals and task controls on the non-activating floating panel', () => {
    const main = readDesktopFile('main.mjs')
    const overlay = readDesktopFile('computer/computerActivityOverlay.ts')
    const preload = readDesktopFile('computer/computerActivityOverlayPreload.cjs')
    const builder = readDesktopFile('electron-builder.yml')
    const system = readDesktopFile('computer/computerSystem.ts')

    expect(overlay).toContain('setFocusable(false)')
    expect(overlay).toContain('setIgnoreMouseEvents(false)')
    expect(overlay).toContain('仅这次允许')
    expect(overlay).toContain('本任务自动')
    expect(overlay).toContain('id="take-control"')
    expect(overlay).toContain('id="resume-control"')
    expect(overlay).toContain('id="stop-control"')
    expect(preload).toContain("ipcRenderer.invoke('desktop:computer-overlay-action'")
    expect(builder).toContain('computer/**/*.cjs')
    expect(main).toContain("electronIpcMain.handle('desktop:computer-overlay-action'")
    expect(main).toContain('computerActivityOverlay?.ownsWebContents(event.sender)')
    expect(main).toContain("COMPUTER_APPROVAL_RESTORE_TOOLS.has(request.toolName || '')")
    expect(main).toContain('restoreObservedTargetAfterApproval()')
    expect(system).toContain('async restoreObservedTargetAfterApproval()')
  })

  it('isolates remote browser content in a main-process system plugin', () => {
    const browser = readDesktopFile('browser/browserSystem.ts')
    const browserSession = readDesktopFile('browser/browserSession.ts')
    const browserCapture = readDesktopFile('browser/browserCapture.ts')
    const browserTools = readDesktopFile('browser/browserTools.ts')

    expect(browserSession).toContain("const BROWSER_PARTITION_PREFIX = 'persist:turboflux-browser-v2'")
    expect(browser).toContain('this.partition = browserPartition(conversationId)')
    expect(browser).toContain('const browserSession = session.fromPartition(this.partition')
    expect(browser).toContain('registerBrowserSession(browserSession')
    expect(browser).toContain('new WebContentsView({')
    expect(browser).toContain('nodeIntegration: false')
    expect(browser).toContain('contextIsolation: true')
    expect(browser).toContain('sandbox: true')
    expect(browser).toContain('webSecurity: true')
    expect(browserSession).toContain('setPermissionRequestHandler')
    expect(browser).not.toContain("requiresSelection: true")
    expect(browser).toContain("Password fields must be filled manually")
    expect(browser).toContain('mkdirSync(directory, { recursive: true })')
    expect(browserTools).toContain("name: 'diagnostics'")
    expect(browserTools).toContain("name: 'assert'")
    expect(browserTools).toContain("name: 'click_at'")
    expect(browserTools).toContain("name: 'open'")
    expect(browserTools).toContain("name: 'tabs'")
    expect(browserTools).toContain("name: 'close'")
    expect(browserTools).toContain("tab_id: { type: 'string' }")
    expect(browser).toContain('redactDiagnosticUrl')
    expect(browser).toContain("send('Input.dispatchMouseEvent'")
    expect(browser).toContain('MAX_BROWSER_DOWNLOAD_BYTES')
    expect(browser).toContain('this.requireCurrentRef(tab, ref)')
    expect(browser).toContain('for (const download of this.activeDownloads) download.cancel()')
    expect(browserCapture).toContain("send('Page.captureScreenshot'")
    expect(browserCapture).not.toContain('capturePage()')
  })

  it('fails closed when the packaged macOS computer helper is unavailable', () => {
    const computer = readDesktopFile('computer/macosComputerDriver.ts')

    expect(computer).toContain('if (app.isPackaged)')
    expect(computer).toContain('signed helper is missing or invalid')
    expect(computer).toContain("access(path, constants.X_OK)")
    expect(computer).toContain('if (signal?.aborted) throw computerOperationAbortError()')
    expect(computer).toContain("error.name = 'AbortError'")
  })

  it('revalidates observed application and window ownership inside native input commands', () => {
    const main = readDesktopFile('main.mjs')
    const system = readDesktopFile('computer/computerSystem.ts')
    const driver = readDesktopFile('computer/macosComputerDriver.ts')
    const helper = readDesktopFile('computer/native/TurboFluxComputerHelper.swift')

    expect(system).toContain('async finishTask(): Promise<void>')
    expect(main).toContain('computerSystem.finishTask()')
    expect(driver).toContain('expectedTarget: ComputerExpectedTarget')
    expect(driver).toContain('expectedTarget: options.expectedTarget')
    expect(helper).toContain('private func validateExpectedTarget')
    expect(helper).toContain('private func validatePointerTarget')
    expect(helper).toContain('private func ensureInputTrusted()')
    expect(helper).toContain('CGSSessionScreenIsLocked')
    expect(helper).toContain('guard CGPreflightPostEventAccess() else { fail("Input control permission is required") }')
    expect(helper).toContain('A complete expected pointer target is required')
    expect(helper).toContain('The target window moved, closed, or changed; observe again')
    expect(helper).toContain('requireFrontmost: false')
    expect(helper).toContain('validatePointerTarget(point: point, expected: request["expectedTarget"] as? JSON)')
    expect(helper).toContain('validatePointerTargets(points: [points[0], points.last!], expected: request["expectedTarget"] as? JSON)')
    expect(helper).toContain('The keyboard target does not match the observed application')
    expect(helper).toContain('The text target does not match the observed application')
    expect(helper.match(/validateExpectedTarget\(request\["expectedTarget"\] as\? JSON\)/g)).toHaveLength(2)
  })

  it('keeps desktop background work in a general-purpose mental model', () => {
    const runtimeHost = readDesktopFile('runtimeHost.ts')
    const experience = readDesktopFile('productExperience.ts')

    expect(runtimeHost).toContain('surfaceSystemPrompt: DESKTOP_EXPERIENCE_SYSTEM_PROMPT')
    expect(runtimeHost).toContain("conversationPrefix: 'desktop'")
    expect(experience).toContain('present background execution through user intent and outcomes rather than terminal mechanics')
    expect(experience).toContain('Do not repeat raw commands')
    expect(experience).toContain('Describe services as local previews or local services')
    expect(experience).toContain('Installed official capability packs are always available to the Agent')
    expect(experience).toContain('they never unlock, hide, or disable tools')
    expect(experience).not.toContain('built-in Browser')
    expect(experience).not.toContain('visual_observe')
    expect(experience).toContain('Treat substantial final responses as finished work products')
    expect(experience).toContain('keep this final response as the task summary')
    expect(experience).toContain('separate verified findings, evidence or source links, uncertainties, and recommended next actions')
    expect(experience).toContain('concise progress narration only at meaningful stage boundaries')
  })

  it('keeps development on a configurable Vite port with main-process watching', () => {
    const vite = readDesktopFile('vite.config.mjs')
    const main = readDesktopFile('main.mjs')
    const devScript = readFileSync(new URL('../../scripts/desktop-dev.mjs', import.meta.url), 'utf8')

    expect(DEFAULT_DESKTOP_DEV_PORT).toBe(15_174)
    expect(resolveDesktopDevServer({})).toEqual({ host: '127.0.0.1', port: 15_174, url: 'http://127.0.0.1:15174' })
    expect(resolveDesktopDevServer({ TURBOFLUX_DESKTOP_PORT: '25174' })).toEqual({ host: '127.0.0.1', port: 25_174, url: 'http://127.0.0.1:25174' })
    expect(() => resolveDesktopDevServer({ TURBOFLUX_DESKTOP_PORT: 'invalid' })).toThrow('between 1024 and 65535')
    expect(vite).toContain('port: desktopServer.port')
    expect(vite).toContain('strictPort: true')
    expect(devScript).toContain('const desktopServer = resolveDesktopDevServer(process.env)')
    expect(devScript).toContain('const desktopUrl = desktopServer.url')
    expect(devScript).toContain('const closeWatchers = [mainEntry, preloadEntry, desktopPathsEntry, runtimeHostEntry]')
    expect(devScript).toContain("const publicRepositoryRoot = resolve(process.env.TURBOFLUX_PUBLIC_REPO")
    expect(devScript).toContain("fileURLToPath(import.meta.resolve('@turboflux/workbench'))")
    expect(devScript).toContain('TURBOFLUX_ELECTRON_USER_DATA_DIR')
    expect(devScript).toContain('`--user-data-dir=${resolve(isolatedUserDataDirectory)}`')
    expect(main).toContain("const hiddenQaWindow = process.env.TURBOFLUX_DESKTOP_QA_HIDDEN === '1'")
    expect(main).toContain('show: !hiddenQaWindow')
    expect(main).toContain('if (hiddenQaWindow)')
    expect(main).toContain('app.dock.hide()')
    expect(devScript).toContain("for (const { directory } of readWorkspaces(publicRepositoryRoot).filter(entry => entry.kind === 'packages'))")
    expect(devScript).toContain("for (const directory of ['browser', 'computer', 'systems', 'terminal', 'remote'])")
    expect(devScript).toContain('buildSharedCore()')
    expect(devScript).toContain('buildDesktopMain()')
    expect(devScript).toContain('rebuildCoreAndRestart')
    expect(devScript).toContain('watch(file, restartElectron)')
    expect(devScript).toContain('const expectedElectronExits = new WeakSet()')
    expect(devScript).toContain('expectedElectronExits.add(child)')
  })

  it('keeps profile archive paths and secrets behind the trusted desktop boundary', () => {
    const main = readDesktopFile('main.mjs')
    const preload = readDesktopFile('preload.cjs')
    const types = readDesktopFile('renderer/types.d.ts')
    const wizard = readDesktopFile('renderer/profileExportWizard.ts')
    const importWizard = readDesktopFile('renderer/profileImportWizard.ts')

    expect(main).toContain("createProfileArchivePathToken(path, 'export')")
    expect(main).toContain("consumeProfileArchivePathToken(requireText(input?.pathToken, 'pathToken'), 'export')")
    expect(main).toContain("result: { ...operation.result, path: undefined }")
    expect(main).toContain('password?.fill(0)')
    expect(main).toContain('profileArchiveTransitionBlocker()')
    expect(preload).toContain("ipcRenderer.invoke('desktop:profile-estimate-export', input)")
    expect(preload).toContain("ipcRenderer.invoke('desktop:profile-choose-export-target')")
    expect(preload).toContain("ipcRenderer.invoke('desktop:profile-start-export', input)")
    expect(types).toContain('chooseProfileExportTarget(): Promise<')
    expect(types).not.toContain('chooseProfileExportTarget(): Promise<string')
    expect(wizard).toContain("['范围', '内容', '隐私', '保护', '确认与导出']")
    expect(wizard).toContain('component.requiresEncryption && selected.has(component.id)')
    expect(wizard).toContain('cancelProfileArchiveOperation')
    expect(wizard).not.toContain('operation!.result?.path')
    expect(main).toContain("createProfileArchivePathToken(path, 'import')")
    expect(main).toContain("resolveProfileArchivePathToken(requireText(input?.pathToken, 'pathToken'), 'import')")
    expect(main).toContain("consumeProfileArchivePathToken(token, 'import')")
    expect(main).toContain('new ProfileArchiveImporter({')
    expect(main.indexOf('}).recoverTransactions()')).toBeLessThan(main.indexOf('const context = registry.activeContext()'))
    expect(main).toContain("ipcMain.handle('desktop:profile-inspect-import'")
    expect(main).toContain("ipcMain.handle('desktop:profile-confirm-rebind'")
    expect(preload).toContain("ipcRenderer.invoke('desktop:profile-inspect-import', input)")
    expect(preload).toContain("ipcRenderer.invoke('desktop:profile-confirm-rebind', input)")
    expect(types).toContain('chooseProfileImportSource(): Promise<')
    expect(types).not.toContain('chooseProfileImportSource(): Promise<string')
    expect(importWizard).toContain("['文件', '认证', '预览', '内容', '安全确认', '创建资料']")
    expect(importWizard).toContain('getProfileImportedConversation')
    expect(importWizard).toContain('acceptMismatch')
    expect(importWizard).not.toContain('source.path')
  })

  it('exposes local profile lifecycle without exposing profile directories', () => {
    const main = readDesktopFile('main.mjs')
    const preload = readDesktopFile('preload.cjs')
    const types = readDesktopFile('renderer/types.d.ts')
    const center = readDesktopFile('renderer/profileCenter.ts')
    const switchCoordinator = readDesktopFile('profileSwitchCoordinator.ts')
    const settingsCopy = readFileSync(new URL('../../packages/profiles/src/profileSettingsCopyService.ts', import.meta.url), 'utf8')

    for (const channel of ['profiles-list', 'profile-create', 'profile-rename', 'profile-switch', 'profile-trash', 'profile-restore']) {
      expect(main).toContain(`ipcMain.handle('desktop:${channel}'`)
    }
    expect(main).toContain('profileLifecycleTransitionBlocker()')
    expect(main).toContain('switchDesktopProfile({')
    expect(main).toContain('resetRuntime: resetRuntimeHost')
    expect(main).toContain('closeRemote: closeRemoteHostManager')
    expect(switchCoordinator).toContain('await options.resetRuntime()')
    expect(switchCoordinator).toContain('await options.closeRemote()')
    expect(switchCoordinator).toContain('options.activate(options.previous.profile.id)')
    expect(main).toContain('copyNonSecretProfileSettings(source, created)')
    expect(settingsCopy).toContain("/(?:api.?key|secret|password|token|authorization|credential)/iu")
    expect(preload).toContain("listLocalProfiles: () => ipcRenderer.invoke('desktop:profiles-list')")
    expect(preload).toContain("switchLocalProfile: profileId => ipcRenderer.invoke('desktop:profile-switch', profileId)")
    expect(types).toContain('interface DesktopLocalProfileSummary')
    expect(types).not.toContain('profileRoot: string')
    expect(types).not.toContain('deviceBoundRoot: string')
    expect(center).toContain('复制当前用户的非秘密设置')
    expect(center).toContain('本机远程设备授权会被永久撤销')
    expect(center).toContain('openRebind(profileId: string)')
    expect(center).toContain('openConversation(conversationId: string)')
    expect(center).toContain('data-profile-conversation')
  })

  it('keeps Stable profile capabilities behind explicit release gates', () => {
    const main = readDesktopFile('main.mjs')
    const handlerSource = (channel: string) => {
      const start = main.indexOf(`ipcMain.handle('desktop:${channel}'`)
      expect(start).toBeGreaterThanOrEqual(0)
      const next = main.indexOf("ipcMain.handle('desktop:", start + 1)
      return main.slice(start, next < 0 ? undefined : next)
    }

    expect(main).toContain('const profileFeatureFlags = resolveProfileFeatureFlags(process.env)')
    expect(main).toContain("requireProfileFeature('conversationDataV2'")
    for (const channel of ['profiles-list', 'profile-create', 'profile-rename', 'profile-switch', 'profile-trash', 'profile-restore']) {
      expect(handlerSource(channel)).toContain("requireProfileFeature('profileCenterV2'")
    }
    for (const channel of [
      'profile-export-options',
      'profile-estimate-export',
      'profile-choose-export-target',
      'profile-start-export',
      'profile-get-archive-operation',
      'profile-cancel-archive-operation',
      'profile-choose-import-source',
      'profile-inspect-import',
      'profile-plan-import',
      'profile-start-import',
      'profile-import-rebind-state',
      'profile-import-conversation',
      'profile-choose-rebind-folder',
      'profile-confirm-rebind',
    ]) {
      expect(handlerSource(channel)).toContain("requireProfileFeature('profileArchiveV2'")
    }
  })
})
