const { contextBridge, ipcRenderer, webUtils } = require('electron')

contextBridge.exposeInMainWorld('turbofluxDesktop', {
  getSnapshot: () => ipcRenderer.invoke('desktop:get-snapshot'),
  listLocalProfiles: () => ipcRenderer.invoke('desktop:profiles-list'),
  getUserProfile: () => ipcRenderer.invoke('desktop:user-profile-get'),
  saveUserProfileName: displayName => ipcRenderer.invoke('desktop:user-profile-name', displayName),
  chooseUserAvatar: () => ipcRenderer.invoke('desktop:user-profile-avatar'),
  getUserActivity: () => ipcRenderer.invoke('desktop:user-activity'),
  createLocalProfile: input => ipcRenderer.invoke('desktop:profile-create', input),
  renameLocalProfile: (profileId, displayName) => ipcRenderer.invoke('desktop:profile-rename', profileId, displayName),
  switchLocalProfile: profileId => ipcRenderer.invoke('desktop:profile-switch', profileId),
  trashLocalProfile: profileId => ipcRenderer.invoke('desktop:profile-trash', profileId),
  restoreLocalProfile: profileId => ipcRenderer.invoke('desktop:profile-restore', profileId),
  getProfileExportOptions: () => ipcRenderer.invoke('desktop:profile-export-options'),
  estimateProfileExport: input => ipcRenderer.invoke('desktop:profile-estimate-export', input),
  chooseProfileExportTarget: () => ipcRenderer.invoke('desktop:profile-choose-export-target'),
  startProfileExport: input => ipcRenderer.invoke('desktop:profile-start-export', input),
  getProfileArchiveOperation: operationId => ipcRenderer.invoke('desktop:profile-get-archive-operation', operationId),
  cancelProfileArchiveOperation: operationId => ipcRenderer.invoke('desktop:profile-cancel-archive-operation', operationId),
  chooseProfileImportSource: () => ipcRenderer.invoke('desktop:profile-choose-import-source'),
  inspectProfileImport: input => ipcRenderer.invoke('desktop:profile-inspect-import', input),
  planProfileImport: input => ipcRenderer.invoke('desktop:profile-plan-import', input),
  startProfileImport: input => ipcRenderer.invoke('desktop:profile-start-import', input),
  getProfileImportRebindState: profileId => ipcRenderer.invoke('desktop:profile-import-rebind-state', profileId),
  getProfileImportedConversation: (profileId, conversationId) => ipcRenderer.invoke('desktop:profile-import-conversation', profileId, conversationId),
  chooseProfileRebindFolder: (profileId, workspaceId) => ipcRenderer.invoke('desktop:profile-choose-rebind-folder', profileId, workspaceId),
  confirmProfileRebind: input => ipcRenderer.invoke('desktop:profile-confirm-rebind', input),
  getRemoteStatus: () => ipcRenderer.invoke('desktop:remote-status'),
  setRemoteEnabled: enabled => ipcRenderer.invoke('desktop:remote-set-enabled', enabled),
  resetRemoteIdentity: () => ipcRenderer.invoke('desktop:remote-reset-identity'),
  setRemotePublicEndpoint: endpoint => ipcRenderer.invoke('desktop:remote-set-public-endpoint', endpoint),
  setRemoteClientUrl: url => ipcRenderer.invoke('desktop:remote-set-client-url', url),
  createRemotePairing: ttlMs => ipcRenderer.invoke('desktop:remote-create-pairing', ttlMs),
  stopRemoteControl: () => ipcRenderer.invoke('desktop:remote-stop-control'),
  approveRemotePairing: requestId => ipcRenderer.invoke('desktop:remote-approve-pairing', requestId),
  rejectRemotePairing: requestId => ipcRenderer.invoke('desktop:remote-reject-pairing', requestId),
  revokeRemoteDevice: deviceId => ipcRenderer.invoke('desktop:remote-revoke-device', deviceId),
  getSettings: forceModels => ipcRenderer.invoke('desktop:get-settings', forceModels),
  previewSettingsModels: update => ipcRenderer.invoke('desktop:preview-settings-models', update),
  saveSettings: update => ipcRenderer.invoke('desktop:save-settings', update),
  getHostPreferences: () => ipcRenderer.invoke('desktop:get-host-preferences'),
  saveHostPreferences: preferences => ipcRenderer.invoke('desktop:save-host-preferences', preferences),
  getBackgroundMedia: () => ipcRenderer.invoke('desktop:get-background-media'),
  chooseBackgroundMedia: () => ipcRenderer.invoke('desktop:choose-background-media'),
  removeBackgroundMedia: () => ipcRenderer.invoke('desktop:remove-background-media'),
  getWindowOpacity: () => ipcRenderer.invoke('desktop:get-window-opacity'),
  setWindowOpacity: opacity => ipcRenderer.invoke('desktop:set-window-opacity', opacity),
  listCommands: () => ipcRenderer.invoke('desktop:list-commands'),
  executeCommand: command => ipcRenderer.invoke('desktop:execute-command', command),
  submitPrompt: (prompt, attachments, capabilities) => ipcRenderer.invoke('desktop:submit-prompt', prompt, attachments, capabilities),
  resendFromTurn: (turnId, prompt) => ipcRenderer.invoke('desktop:resend-from-turn', turnId, prompt),
  recordDraft: draft => ipcRenderer.invoke('desktop:record-draft', draft),
  openExternal: url => ipcRenderer.invoke('desktop:open-external', url),
  browserGetState: () => ipcRenderer.invoke('desktop:browser-get-state'),
  browserShow: () => ipcRenderer.invoke('desktop:browser-show'),
  browserHide: () => ipcRenderer.invoke('desktop:browser-hide'),
  browserNewTab: url => ipcRenderer.invoke('desktop:browser-new-tab', url),
  browserActivateTab: tabId => ipcRenderer.invoke('desktop:browser-activate-tab', tabId),
  browserCloseTab: tabId => ipcRenderer.invoke('desktop:browser-close-tab', tabId),
  browserNavigate: (url, tabId) => ipcRenderer.invoke('desktop:browser-navigate', url, tabId),
  browserBack: tabId => ipcRenderer.invoke('desktop:browser-back', tabId),
  browserForward: tabId => ipcRenderer.invoke('desktop:browser-forward', tabId),
  browserReload: tabId => ipcRenderer.invoke('desktop:browser-reload', tabId),
  browserSetBounds: bounds => ipcRenderer.invoke('desktop:browser-set-bounds', bounds),
  terminalList: () => ipcRenderer.invoke('desktop:terminal-list'),
  terminalCreate: dimensions => ipcRenderer.invoke('desktop:terminal-create', dimensions),
  terminalRead: (sessionId, sinceSeq) => ipcRenderer.invoke('desktop:terminal-read', sessionId, sinceSeq),
  terminalWrite: (sessionId, data) => ipcRenderer.invoke('desktop:terminal-write', sessionId, data),
  terminalResize: (sessionId, cols, rows) => ipcRenderer.invoke('desktop:terminal-resize', sessionId, cols, rows),
  terminalClose: sessionId => ipcRenderer.invoke('desktop:terminal-close', sessionId),
  computerGetState: () => ipcRenderer.invoke('desktop:computer-get-state'),
  computerRefresh: () => ipcRenderer.invoke('desktop:computer-refresh'),
  computerRequestPermission: kind => ipcRenderer.invoke('desktop:computer-request-permission', kind),
  computerOpenPermissionSettings: kind => ipcRenderer.invoke('desktop:computer-open-permission-settings', kind),
  computerRelaunch: () => ipcRenderer.invoke('desktop:computer-relaunch'),
  computerTakeControl: () => ipcRenderer.invoke('desktop:computer-take-control'),
  computerResumeControl: () => ipcRenderer.invoke('desktop:computer-resume-control'),
  computerEmergencyStop: () => ipcRenderer.invoke('desktop:computer-emergency-stop'),
  stop: () => ipcRenderer.invoke('desktop:stop'),
  pause: () => ipcRenderer.invoke('desktop:pause'),
  resume: () => ipcRenderer.invoke('desktop:resume'),
  controlWorkStep: (taskId, action) => ipcRenderer.invoke('desktop:control-work-step', taskId, action),
  resolveRequest: (requestId, response) => ipcRenderer.invoke('desktop:resolve-request', requestId, response),
  newConversation: () => ipcRenderer.invoke('desktop:new-conversation'),
  newConversationInProject: id => ipcRenderer.invoke('desktop:new-project-conversation', id),
  switchConversation: id => ipcRenderer.invoke('desktop:switch-conversation', id),
  deleteConversation: id => ipcRenderer.invoke('desktop:delete-conversation', id),
  renameConversation: (id, title) => ipcRenderer.invoke('desktop:rename-conversation', id, title),
  gitStage: paths => ipcRenderer.invoke('desktop:git-stage', paths),
  gitUnstage: paths => ipcRenderer.invoke('desktop:git-unstage', paths),
  gitCommit: (message, paths) => ipcRenderer.invoke('desktop:git-commit', message, paths),
  gitCreateBranch: (name, startPoint) => ipcRenderer.invoke('desktop:git-create-branch', name, startPoint),
  gitSwitchBranch: name => ipcRenderer.invoke('desktop:git-switch-branch', name),
  gitRestore: (paths, source) => ipcRenderer.invoke('desktop:git-restore', paths, source),
  gitPush: (remote, branch, setUpstream) => ipcRenderer.invoke('desktop:git-push', remote, branch, setUpstream),
  gitDiff: (path, scope) => ipcRenderer.invoke('desktop:git-diff', path, scope),
  chooseProjectFolder: () => ipcRenderer.invoke('desktop:choose-project-folder'),
  addProject: input => ipcRenderer.invoke('desktop:add-project', input),
  renameProject: (id, name) => ipcRenderer.invoke('desktop:rename-project', id, name),
  removeProject: id => ipcRenderer.invoke('desktop:remove-project', id),
  createAutomation: input => ipcRenderer.invoke('desktop:create-automation', input),
  previewAutomationSchedule: (schedule, timezone, count) => ipcRenderer.invoke('desktop:preview-automation-schedule', schedule, timezone, count),
  listAutomationDefinitions: query => ipcRenderer.invoke('desktop:list-automation-definitions', query),
  getAutomationDefinition: id => ipcRenderer.invoke('desktop:get-automation-definition', id),
  saveAutomationDraft: input => ipcRenderer.invoke('desktop:save-automation-draft', input),
  validateAutomationDefinition: id => ipcRenderer.invoke('desktop:validate-automation-definition', id),
  publishAutomationDefinition: (id, expectedRevision) => ipcRenderer.invoke('desktop:publish-automation-definition', id, expectedRevision),
  setAutomationDefinitionStatus: (id, status) => ipcRenderer.invoke('desktop:set-automation-definition-status', id, status),
  rollbackAutomationDefinition: (id, targetRevision, expectedRevision) => ipcRenderer.invoke('desktop:rollback-automation-definition', id, targetRevision, expectedRevision),
  resetAutomationContinuationConversation: (id, expectedRevision) => ipcRenderer.invoke('desktop:reset-automation-continuation-conversation', id, expectedRevision),
  listAutomationRuns: query => ipcRenderer.invoke('desktop:list-automation-runs', query),
  getAutomationRun: runId => ipcRenderer.invoke('desktop:get-automation-run', runId),
  setAutomationRunPinned: (runId, pinned) => ipcRenderer.invoke('desktop:set-automation-run-pinned', runId, pinned),
  resolveAutomationApproval: (approvalId, response) => ipcRenderer.invoke('desktop:resolve-automation-approval', approvalId, response),
  updateAutomation: (id, patch) => ipcRenderer.invoke('desktop:update-automation', id, patch),
  removeAutomation: id => ipcRenderer.invoke('desktop:remove-automation', id),
  archiveAutomationDefinition: (id, options) => ipcRenderer.invoke('desktop:archive-automation-definition', id, options),
  duplicateAutomation: id => ipcRenderer.invoke('desktop:duplicate-automation', id),
  runAutomation: id => ipcRenderer.invoke('desktop:run-automation', id),
  testAutomation: id => ipcRenderer.invoke('desktop:test-automation', id),
  retryAutomationRun: (id, runId) => ipcRenderer.invoke('desktop:retry-automation-run', id, runId),
  recoverAutomationRun: (runId, action) => ipcRenderer.invoke('desktop:recover-automation-run', runId, action),
  abandonAutomationRunRecovery: runId => ipcRenderer.invoke('desktop:abandon-automation-run-recovery', runId),
  cancelAutomationRun: id => ipcRenderer.invoke('desktop:cancel-automation-run', id),
  takeOverAutomationRun: id => ipcRenderer.invoke('desktop:take-over-automation-run', id),
  previewArtifact: (id, purpose = 'full') => ipcRenderer.invoke('desktop:preview-artifact', id, purpose),
  previewImageAttachment: (path, purpose = 'full') => ipcRenderer.invoke('desktop:preview-image-attachment', path, purpose),
  openArtifact: id => ipcRenderer.invoke('desktop:open-artifact', id),
  revealArtifact: id => ipcRenderer.invoke('desktop:reveal-artifact', id),
  exportArtifact: id => ipcRenderer.invoke('desktop:export-artifact', id),
  exportImageAttachment: path => ipcRenderer.invoke('desktop:export-image-attachment', path),
  removeArtifact: id => ipcRenderer.invoke('desktop:remove-artifact', id),
  listPlugins: () => ipcRenderer.invoke('desktop:list-plugins'),
  retryPersistence: () => ipcRenderer.invoke('desktop:retry-persistence'),
  exportRecovery: () => ipcRenderer.invoke('desktop:export-recovery'),
  listWorkPacks: () => ipcRenderer.invoke('desktop:list-work-packs'),
  refreshWorkPacks: () => ipcRenderer.invoke('desktop:refresh-work-packs'),
  installLocalPlugin: () => ipcRenderer.invoke('desktop:install-local-plugin'),
  setWorkPackEnabled: (workPackId, enabled) => ipcRenderer.invoke('desktop:set-work-pack-enabled', workPackId, enabled),
  uninstallWorkPack: workPackId => ipcRenderer.invoke('desktop:uninstall-work-pack', workPackId),
  reconnectMcp: name => ipcRenderer.invoke('desktop:reconnect-mcp', name),
  acknowledgeNotification: id => ipcRenderer.invoke('desktop:acknowledge-notification', id),
  listMemories: (filters, forceReload) => ipcRenderer.invoke('desktop:list-memories', filters, forceReload),
  rememberMemory: input => ipcRenderer.invoke('desktop:remember-memory', input),
  updateMemory: (id, update) => ipcRenderer.invoke('desktop:update-memory', id, update),
  forgetMemory: (id, reason) => ipcRenderer.invoke('desktop:forget-memory', id, reason),
  chooseFiles: () => ipcRenderer.invoke('desktop:choose-files'),
  importFiles: paths => ipcRenderer.invoke('desktop:import-files', paths),
  importClipboardImage: (base64, mime, filename) => ipcRenderer.invoke('desktop:import-clipboard-image', base64, mime, filename),
  pathForFile: file => webUtils.getPathForFile(file),
  chooseWorkspace: () => ipcRenderer.invoke('desktop:choose-workspace'),
  chooseAutomationWorkspace: () => ipcRenderer.invoke('desktop:choose-automation-workspace'),
  onRuntimeEvent: listener => {
    const handler = (_event, payload) => listener(payload)
    ipcRenderer.on('desktop:runtime-event', handler)
    return () => ipcRenderer.removeListener('desktop:runtime-event', handler)
  },
  onNavigationIntent: listener => {
    const handler = (_event, payload) => listener(payload)
    ipcRenderer.on('desktop:navigation-intent', handler)
    return () => ipcRenderer.removeListener('desktop:navigation-intent', handler)
  },
  onBrowserEvent: listener => {
    const handler = (_event, payload) => listener(payload)
    ipcRenderer.on('desktop:browser-event', handler)
    return () => ipcRenderer.removeListener('desktop:browser-event', handler)
  },
  onTerminalEvent: listener => {
    const handler = (_event, payload) => listener(payload)
    ipcRenderer.on('desktop:terminal-event', handler)
    return () => ipcRenderer.removeListener('desktop:terminal-event', handler)
  },
  onComputerEvent: listener => {
    const handler = (_event, payload) => listener(payload)
    ipcRenderer.on('desktop:computer-event', handler)
    return () => ipcRenderer.removeListener('desktop:computer-event', handler)
  },
})
