import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const workflow = readFileSync(new URL('../../.github/workflows/ci.yml', import.meta.url), 'utf8')
const script = readFileSync(new URL('../../scripts/desktop-profile-hidden-qa.mjs', import.meta.url), 'utf8')

describe('hidden profile acceptance contract', () => {
  it('accepts material blur or a translucent platform fallback without contradicting the surface hierarchy', () => {
    expect(script).toContain('styles.backdropFilter')
    expect(script).toContain('styles.webkitBackdropFilter')
    expect(script).toContain('materialBackdrop = hasBackdrop(wallpaperMaterial.overlayBackdrop) || hasBackdrop(wallpaperMaterial.shellBackdrop)')
    expect(script).toContain('materialFallback = translucent(wallpaperMaterial.shell) && translucent(wallpaperMaterial.header) && translucent(wallpaperMaterial.nav)')
    expect(script).toContain('(materialBackdrop || materialFallback)')
    expect(script).toContain('transparent(wallpaperMaterial.content)')
    expect(script).not.toContain("wallpaperMaterial.overlayBackdrop === 'none'")
    expect(script).not.toContain('invariant(transparent(wallpaperMaterial.shell)')
    expect(script).not.toContain('new BrowserWindow')
    expect(script).toContain('windowsHide: true')
    expect(script).toContain("TURBOFLUX_DESKTOP_QA_HIDDEN: '1'")
  })

  it('atomically writes sanitized schema v2 artifacts without leaking failure diagnostics', () => {
    expect(script).toContain('schemaVersion: 2')
    expect(script).toContain('provenance: captureGithubActionsProvenance()')
    expect(script).toContain("argument === '--packaged'")
    expect(script).toContain('discoverPackagedExecutable')
    expect(script).toContain('verifyPackagedExecutableIdentity')
    expect(script).toContain("applicationMode === 'packaged-app'")
    expect(script).toContain('packageEvidence: verifiedPackage')
    expect(script).toContain('writeEvidenceFileAtomically(join(screenshotRoot, filename)')
    expect(script).toContain("writeSourceEvidenceReportAtomically(join(screenshotRoot, 'result.json'), result)")
    expect(script).toContain('return filename')
    expect(script).toContain("process.stderr.write('Profile hidden QA failed\\n')")
    expect(script).not.toContain("writeFile(join(screenshotRoot, 'result.json')")
    expect(script).not.toContain('process.stderr.write(output.join(')
    expect(script).not.toContain('Preserved hidden QA root: ${qaRoot}')
    expect(script).toContain("child.once('error', () => {})")
    expect(script).toContain('`${process.platform}-${process.arch}`')
    expect(script).toContain('rm(profileEvidenceRoot, { recursive: true, force: true })')
  })

  it('preserves generated Profile artifacts when later acceptance steps fail', () => {
    const packageJob = workflow.slice(workflow.indexOf('  desktop-package:'), workflow.indexOf('  profile-evidence:'))
    expect(packageJob).toMatch(/- uses: actions\/upload-artifact@v4\n\s+if: always\(\)\n\s+with:\n\s+name: profile-archive-smoke-/u)
    expect(packageJob).toMatch(/- uses: actions\/upload-artifact@v4\n\s+if: always\(\)\n\s+with:\n\s+name: profile-hidden-qa-/u)
    expect(packageJob).toContain('npm run qa:profiles:hidden -- --packaged')
    expect(packageJob).toContain('xvfb-run --auto-servernum npm run qa:profiles:hidden -- --packaged')
    expect(packageJob).toContain("runner.os != 'Linux' && (success() || failure())")
    expect(packageJob).toContain("runner.os == 'Linux' && (success() || failure())")
    const evidenceJob = workflow.slice(workflow.indexOf('  profile-evidence:'), workflow.indexOf('  desktop-package-evidence:'))
    expect(evidenceJob).toContain('needs: desktop-package')
    expect(evidenceJob).toContain('if: always()')
    expect(evidenceJob).toContain('continue-on-error: true')
    expect(evidenceJob).toContain('pattern: profile-hidden-qa-*')
    expect(evidenceJob).toContain('path: apps/desktop/generated/profile-qa')
    expect(evidenceJob).toContain('merge-multiple: true')
    expect(evidenceJob).toContain('pattern: desktop-package-report-*')
    expect(evidenceJob).toContain('path: apps/desktop/generated/package-evidence')
    expect(evidenceJob).toContain('npm run verify:profiles:hidden:evidence')
    expect(evidenceJob).toContain('profile-hidden-cross-platform-evidence-report')
  })
})
